* LaTeX Preamble                                                     :ignore:
#+TITLE: IPSP078 - Legal Aspects of Electronic Commerce
#+AUTHOR: Nyameko Lisa
#+DATE: 19 October 2018
#+SUBTITLE: Portfolio Exam: 691859
#+LATEX_HEADER: \pagenumbering{roman}
#+LATEX_HEADER: \usepackage[margin=0.80in]{geometry}
#+LATEX_HEADER: \usepackage[backend=biber, style=ieee, url=false, dashed=false]{biblatex}
#+LATEX_HEADER: \usepackage{float}
#+LATEX_HEADER: \usepackage[super,negative]{nth}
#+LATEX_HEADER: \usepackage[capitalise]{cleveref}
#+LATEX_HEADER: \usepackage{pst-node,transparent,ragged2e}
#+LATEX_HEADER: \addbibresource{/home/nlisa/.spacemacs.d/org-files/bibliography.bib}
#+LATEX_HEADER: \DeclareFieldFormat[inproceedings]{citetitle}{\textit{#1}}
#+LATEX_HEADER: \DeclareFieldFormat[inproceedings]{title}{\textit{#1}}
#+LATEX_HEADER: \DeclareFieldFormat[misc]{citetitle}{#1}
#+LATEX_HEADER: \DeclareFieldFormat[misc]{title}{#1}
#+LATEX_HEADER: \renewcommand*{\bibpagespunct}{%
#+LATEX_HEADER:   \ifentrytype{inproceedings}
#+LATEX_HEADER:     {\addspace}
#+LATEX_HEADER:     {\addcomma\space}}
#+LATEX_HEADER: \AtEveryCitekey{\ifuseauthor{}{\clearname{author}}}
#+LATEX_HEADER: \AtEveryBibitem{\ifuseauthor{}{\clearname{author}}}

#+OPTIONS: toc:nil
#+LATEX_HEADER: \SpecialCoor

# Institution
#+BEGIN_EXPORT latex
\addvspace{110pt}
\centering{
\pnode(0.5\textwidth,-0.5\textheight){thisCenter}
\rput(thisCenter){%\transparent{0.25}
\includegraphics[width=2.7in]{/home/nlisa/course/llb/wipo-unisa/UNISACoatofArms.eps}}}
#+END_EXPORT

#+LaTeX: \justifying
#+LaTeX: \addvspace{110pt}
* Declaration
  :PROPERTIES:
   :UNNUMBERED: t
  :END:
  I know that plagiarism is to use someone else’s work and pass it off as my own.\\
  I know that plagiarism is wrong.\\
  I confirm that this assignment is my own work.\\
  I have acknowledged in the bibliography accompanying the assignment all the sources that I have used.\\
  I have not directly copied without acknowledgment anything from the Internet or from any other source.\\
  I have indicated every quotation and citation in a footnote or bracket linked to that quotation.\\
  I have not allowed anyone else to copy my work and to pass it off as their own work.\\
  I understand that if any unacknowledged copying whatsoever appears in my assignment I will receive zero per cent for the assignment.\\
  I am aware of the UNISA policy on plagiarism and understand that disciplinary proceedings can be instituted against me by UNISA if I contravene this policy.\\
  I indicate my understanding and acceptance of this declaration by
  entering my name here under:
    - Name: *Nyameko Lisa* (Student Number: *7874-909-3*)

** NOTE
Please note that footnotes will be denoted as [fn::This is a footnote.] and will
appear at the bottom of the page.\\
References will be denoted by cite:rsa02_elect_comm_trans_act and a numerically
organized citation list will appear at the end of the document.
\newpage

\pagenumbering{arabic}
* Ofentse approaches you and wants your advise on the following: [25]

As per the provisions of [section 1]cite:rsa02_elect_comm_trans_act together
with [section 1(q)]cite:rsa12_elect_comm_trans_amend_bill the data base will be
understood to constitute either *`data'* or a *`data message'*, Ofentse as
the compiler of the database will be understood to be the *`data controller'*
and his clients whose personal information constitute the content of the
database will be understood to be *`data subjects'*.

** The requirements that the databases must meet in order to enjoy copyright protection. (10)

As a Paris Convention Member State the provisions of [article
9(1)]cite:wto17_trips, [section 5]cite:rsa78_copyrightact [article
1(2)]cite:eurlex00_elec_commerce, [article 5(2)]cite:wipo86_berne and [article
1(4)]cite:wipo96_copyright_treaty dictate that the statues of the Republic shall
govern international copyright protection as it pertains to the Internet.
Moreover as per the provisions of [section 1(1)]cite:rsa78_copyrightact in the
context of copyright law a database i.e. /tables and compilations of data stored
or embodied in a computer or medium used in conjunction with a computer,/ will
be considered to be a *`literary work'* and as a such it will be eligible for
copyright per the provisions of [section 2(1)(a)]cite:rsa78_copyrightact
provided Ofentse can demonstrate that his database is indeed original, and as
per [section 2(2)]cite:rsa78_copyrightact that the database can be recorded in
digital data. Furthermore copyright shall be conferred to the database if
Ofentse can demonstrate that he meets the /`inherent'/ and /`formal'/ or
/`statutory'/ requirements for copyright to subsist in his work.
- Inherent Requirements
  - The requirement of material embodiment is clearly satisfied as the
    work exists in material, albeit electronic form.
  - As per [article 9(2)]cite:wto17_trips and [article
    2]cite:wipo96_copyright_treaty, it can be argued that the database is a
    /`particular form of expression of thought'/, thus satisfying the
    requirement of originality.
- Formal Requirements
  - It is implied that he is either a citizen of, or domiciled in, or a
    permanent resident of [section 3(1)(a)]cite:rsa78_copyrightact, a Berne
    Convention country [section 3, section 37]cite:wipo86_berne, meaning that he
    was a *qualified person* at the time of creation of the work and thus making
    him the author.
  - Moreover it is implied that the work was first made in South Africa,
    [section 4]cite:rsa78_copyrightact, and therefore meets the statutory
    requirements for the subsistence of copyright in the work.

** The provisions of the Electronic Communications and Transactions Act 2002 which limits the liability of the Internet service providers. (15)

As per the provisions of the ETC Act cite:rsa02_elect_comm_trans_act, a service
provider is not liable for damages arising from said service provider for
providing access to information system services or wireless applications
services [section 70]cite:rsa02_elect_comm_trans_act together with [section
36]cite:rsa12_elect_comm_trans_amend_bill, or for operating facilities as a
/`mere conduit'/ [section 73]cite:rsa02_elect_comm_trans_act together with
[section 38]cite:rsa12_elect_comm_trans_amend_bill, /`caching purposes'/
[section 74]cite:rsa02_elect_comm_trans_act together with [section
39]cite:rsa12_elect_comm_trans_amend_bill and /`hosting services'/ [section
75]cite:rsa02_elect_comm_trans_act. The eligibility for the limitation of
liability of a service provider is dependent on their membership with a
recognized Representative body as per [sections 71 and
72]cite:rsa02_elect_comm_trans_act together with [section
37]cite:rsa12_elect_comm_trans_amend_bill Moreover the Act explicitly excludes
service providers' obligation from monitoring data, as per [section
78]cite:rsa02_elect_comm_trans_act.

* Advise the Committee on the following issues [25]:

** Does EduCate's marketing practice constitute spam according to South African law? If so, discuss those legislative provisions and state whether they adequately protect consumers? [15]

Given that the recipients email addresses were retrieved from public websites,
and that there have been consumers who've lodged complaints against EduCate CC,
EduCate's bulk email newsletters constitute commercially motivated
direct-marketing by means of unsolicited electronic communications, thus
amounting to spam
cite:hermann14_direct_marketing_vs_spam,tladi08_reg_unsol_comm. As per the
provisions of [section 45]cite:rsa02_elect_comm_trans_act together with [section
23]cite:rsa12_elect_comm_trans_amend_bill recipients of unsolicited
communications are able to opt-out of future communications and may request
information on where their personal information and contact details were
obtained. Moreover as per the provisions of [section
45(3,4)]cite:rsa02_elect_comm_trans_act together with [section
23]cite:rsa12_elect_comm_trans_amend_bill, anyone failing to comply or
persisting to send unsolicited commercial communications to a person whose
advised that such communication is unwelcome, is guilty of an offense and liable
on conviction to penalties. Moreover as per the provisions of [sections 50 &
51]cite:rsa02_elect_comm_trans_act together with [section
26]cite:rsa12_elect_comm_trans_amend_bill, acting as a data controller, all
electronic requests, collection, collation, processing, storage or disclosure of
any personal information of their `prospective clients' is prohibited with the
clients' express written consent.\\

As per the provisions of [section 11(1, 2)]cite:rsa08_cpa every
person has the right to privacy which includes the right to restrict unwanted
direct marketing through retrospective refusal to accept or request
discontinuance or preemptive blockage of said unsolicited messages. Moreover as
per the provisions of [section 11(3 - 5)]cite:rsa08_cpa
consumers may register either a general or specific preemptive block against any
communications primarily for the purpose of direct marketing.\\

As per the provisions of [section 69(1)]cite:rsa13_popi stipulates that for the
purposes of direct marketing by any form of electronic communication, the
processing of personal information of a data subject is prohibited unless the
data subject has given their consent. Moreover as per [subsections (2, 3) of
section 69]cite:rsa13_popi a responsible party may approach existing customers
or prospective consumers on a single occasion provided that said consumers have
not previously withheld such consent. Lastly as per the provisions of [section
69(4)]cite:rsa13_popi stipulates that a responsible party must in their
communications include identifying details of either the sender or party on
behalf of whom the information has been sent, and a mechanism for the cessation
of further messages.

** Choose one country that regulates spam in its jurisdiction and give a detailed discussion on the country's initiatives. Also note what SA can learn from that jurisdiction regarding the issues of spam. (10)

Canada's Anti-Spam Legislation cite:ca10_anti_spam_act was enacted on 15
December 2010 and its purpose is to promote the efficiency and adaptability of
the Canadian economy [section 3]cite:ca10_anti_spam_act by regulating a range of
online activities including spam messaging, spyware distribution, fishing,
fraudulent as well as other deceptive and harmful online threats and practices.
The legislation adopts a holistic approach in encompassing through
implementation within this Act amendments to their corresponding legislation:
the Canadian Radio-Television and Telecommunications Commission Act
cite:ca85_radio_tv_telecomms_act, the Canadian Competition Act
cite:ca85_comp_act, the Canadian Personal Information Protection and Electronic
Documents Act cite:ca00_popi_act and the Canadian Telecommunications Act
cite:ca93_telecomms_act.\\

The introductory [sections 1 - 5]cite:ca10_anti_spam_act deal with the
interpretive definitions; conflicting provisions and the precedence of this Act;
the purpose of the Act, scope and applicability of the Act respectively.
[Sections 6 - 13]cite:ca10_anti_spam_act detail the *Requirements and
Prohibitions* related to electronic messages during the conduct of commercial
activities, namely: unsolicited electronic messages [section
6]cite:ca10_anti_spam_act, alteration of transmission data [section
7]cite:ca10_anti_spam_act, installation of computer programs [section
8]cite:ca10_anti_spam_act, the jurisdiction where the contravention of the
corresponding sections applies [sections 9, 12]cite:ca10_anti_spam_act, the
requirements for express consent to perform regulated and prohibited actions
[section 10]cite:ca10_anti_spam_act, mandatory provision of an unsubscribe
mechanism with respect to unsolicited messages [section
11]cite:ca10_anti_spam_act and lastly how the burden of proof vests with the
alleged perpetrator of a prohibited activity to demonstrate that they indeed had
express consent to perform said activity [section
13]cite:ca10_anti_spam_act.\\

*Administrative Monetary Penalties* are articulated in [sections
14 - 40]cite:ca10_anti_spam_act, namely: the appointment of a designated authority
[section 14]cite:ca10_anti_spam_act; their authority to demand preservation of
and notice to produce infringing electronic data [section
15 - 18]cite:ca10_anti_spam_act; issuance and execution of warrants, including
details regrading use of force and entry onto private property [section
19]cite:ca10_anti_spam_act; notification and determination of responsibility for
the contravention of the prohibitions amounting to violations for which one may
be found liable to an administrative monetary penalty to the value of $1,000,000
in the case of an individual and $10,000,000 in the case of any other person,
are considered in [sections 20 - 26]cite:ca10_anti_spam_act, these sections also
detail how the penalties are not intended to be punitive, but rather they are
intended to encourage compliance; the appeals process to the Federal Court of
Appeals, the recovery of penalties and other amounts, and the rules regarding
violations are the purview of [sections 27 - 33]cite:ca10_anti_spam_act, including
/vicarious liability/ where an employer may be liable for violations committed
by their employee during the course of their employment; general provisions
regarding judicial powers, rules of procedure, evidence, publication and
enforcement are dealt with in [sections 34 - 40]cite:ca10_anti_spam_act.\\

Notice and issuance of an *Injunction* is outlined in [section
41]cite:ca10_anti_spam_act, whilst matters relating to *Offenses* are
articulated in [section 42 - 46]cite:ca10_anti_spam_act. These include offenses
resulting from non-compliance [section 42]cite:ca10_anti_spam_act with respect
to refusal or failure to comply with either a preservation demand [section
15]cite:ca10_anti_spam_act, presentation notification [section
17]cite:ca10_anti_spam_act, and/or a warrant issued as per [section
19(4)]cite:ca10_anti_spam_act; obstruction and falsification of information
[section 43]; implicit and vicarious liability of directors and officers of
corporations and employers in general [sections 44 & 45]cite:ca10_anti_spam_act;
with the monetary details for offenses detailed in [section
46]cite:ca10_anti_spam_act.\\

With regards to actual litigation and the *Private Right of Action* [sections
47 - 49]cite:ca10_anti_spam_act deal with the application process; [sections
50 - 51]cite:ca10_anti_spam_act provide details for the court hearing and their
respective orders; and [sections 52 - 55]cite:ca10_anti_spam_act describe the
rules about contraventions and re-viewable conduct. The remaining sections
details statutory regulations, as well as parliamentary and ministerial roles
and responsibilities. Where [sections 56 - 61]cite:ca10_anti_spam_act described
the process for the *Consultation and Disclosure of Information*, be it by an
organization [section 56 - 57]cite:ca10_anti_spam_act; by a Commission [sections
58 - 59]cite:ca10_anti_spam_act; by the government of a foreign state [section
60]cite:ca10_anti_spam_act; and the reports to the Ministry of Industry [section
61]cite:ca10_anti_spam_act.\\

The Canadian Anti-Spam Law cite:ca10_anti_spam_act is arguably one of the most
stringent in the world and should conceivably have a significant impact on
reducing spa in that jurisdiction, in that it constitutes specific legislation
with a targeted purpose [section 3]cite:ca10_anti_spam_act. As opposed to a
fragmented, piecemeal collection of a limited amount of provisions
cite:hermann14_direct_marketing_vs_spam,tladi08_reg_unsol_comm which are
secondary to the aims of the statues within which they are contained
cite:rsa02_elect_comm_trans_act,rsa12_elect_comm_trans_amend_bill,rsa08_cpa,rsa13_popi
as is the case with the instruments within the Republic.

* Advise Kate on the following: [25]

** Whether the requirements of an electronic signature have been met by clicking on the icon ``Submit Order''. (10)

As per the provisions of [section 1]cite:rsa02_elect_comm_trans_act together
with [section 1(q)(b)]cite:rsa12_elect_comm_trans_amend_bill, the act of
clicking the "Submit Order" icon will constitute the generation of a *`data
message'* in that it is a form of electronic communication stored as a record.
In the matter citetitle:Cachalia15_spring_forest_v_wilberry
cite:Cachalia15_spring_forest_v_wilberry, which was an appeal concerning a
series of emails purporting to the consensual cancellation of the written
agreements between the parties. Stipulated within those written agreements was
that `consensual cancellation' to be effected *in writing and signed by both
parties*. As per the provisions of [sections 11, 12 and
13]cite:rsa02_elect_comm_trans_act, statutory regulations of the Republic afford
legal recognition to transactions concluded electronically via email. The
SCA[fn::Supreme Court of Appeals.] was required to consider whether the dispute
arising from the exchange of emails between the parties, did indeed satisfy the
*writing* [section 12]cite:rsa02_elect_comm_trans_act and *signature* [section
13]cite:rsa02_elect_comm_trans_act requirements, thereby constituting legal
consensual cancellation.\\

The SCA held that the stipulations for the requirement of an `advanced
electronic signature' [section 13(1)]cite:rsa02_elect_comm_trans_act did not
apply to the circumstances of this case, whereas however the less restrictive
requirements of an 'electronic signature' [section
13(3)]cite:rsa02_elect_comm_trans_act do indeed apply. Wherein it need only be
demonstrated that the requirement is indeed met if a method of electronic
signature used to identify a party and indicate their approval of the contained
information [section 13(3)(a)]cite:rsa02_elect_comm_trans_act, and that the
method was indeed `appropriately reliable' for the intended purposes of the
information communicated [section 13(3)(b)]cite:rsa02_elect_comm_trans_act. In
the SCA's analysis of [section 13(3)]cite:rsa02_elect_comm_trans_act, Justice
Cachali argued [paragraph 19]cite:Cachalia15_spring_forest_v_wilberry:
#+BEGIN_QUOTE
\textit{‘The respondent submits that the phrase: “Where the signature of a person is required by law” (emphasis added) in s 13(1) it should be interpreted not only to include formalities required by statute but must also incorporate instances where parties to an agreement impose their own formalities on a contract, as in this case. And, so the contention goes, because the parties required their signatures for the contracts to be cancelled the requirement could only be satisfied by the use of an advanced electronic signature as contemplated in s 13(1), which did not occur in this case.’}
#+END_QUOTE
The SCA ordered that the appeal be upheld with costs, and that the order of the
HC be set aside and dismissed with costs [paragraph
32]cite:Cachalia15_spring_forest_v_wilberry. Similarly as per the provisions of
[section 13(3)]cite:rsa02_elect_comm_trans_act there did indeed exist a method
to identify Kate and to indicate her approval of the information communicated:
during the procurement process she'd read the retailer's terms and conditions,
and she /`must'/[fn::This is a reasonable assumption considering the manner in
which online retailers conduct their enterprises.] have been logged in to her
uniquely registered profile. Moreover that this was as reliable as was
appropriate for those purposes. Therefore one can conclude that the
requirements for an electronic signature have indeed been met by clicking the
`Submit Order' icon.

** Does South African law recognize this type of transaction, and what are the legal implications thereof? (10)

Within the ambit of American case law in the matter
citetitle:leval04_register_v_verio, cite:leval04_register_v_verio, the court
described a click-wrap license with respect to software installation and/or
usage, even though the license in questions was distinguished from a click-wrap
license where Judge Pierre N. Leval pointed out that:
#+BEGIN_QUOTE
\textit{`Essentially, under a click-wrap agreement licensees are presented with the proposed license terms and forced to expressly and unambiguously manifest either assent or rejection prior to being given access to the product.'}
#+END_QUOTE
As per the provisions of [section 11]cite:rsa02_elect_comm_trans_act together
with those of [section 8]cite:rsa12_elect_comm_trans_amend_bill data messages
enjoy legal recognition. In addition, as per the provisions of [section
22(1)]cite:rsa02_elect_comm_trans_act an agreement is not without legal force
and effect merely because it was concluded either partially or in whole through
data messages. Moreover as per the provisions of [section
24]cite:rsa02_elect_comm_trans_act, clicking `Submit Order' constitutes and
expression of intent or other statement that is legally enforceable in that it
is in the form of a data message or other electronic means from which one's
intentions or other statements can be inferred. Lastly, as per the provisions of
[section 26]cite:rsa02_elect_comm_trans_act acknowledgment of receipt of a data
massage is not a prerequisite to establish legal effect of that message. It can
therefore reasonably be argued that these type of transactions are indeed
recognized in South African law.\\

Referring again to the matter heard in cite:Cachalia15_spring_forest_v_wilberry,
the SCA held that courts seek to determine whether the method of signature used
fulfills the function of a signature which is to authenticate the identity of a
signatory and to appropriately validate it's authenticity, rather than insisting
on the form a signature may assume. The judgment held that the approach of
courts has in general been pragmatic and not overly formal, citing a case
[paragraph 148F-G]cite:elec_signa63_putter_v_provincial_insurance where the
courts have accepted any mark made by a person attesting to a document
[paragraph 25]cite:Cachalia15_spring_forest_v_wilberry:
#+BEGIN_QUOTE
\textit{`In the days before electronic communication, the courts were willing to accept any mark made by a person for the purpose of attesting a document, or identifying it as his act, to be a valid signature. They went even further and accepted a mark made by a magistrate for a witness, whose participation went only as far as symbolically touching the magistrate’s pen.'}
#+END_QUOTE
The SCA held that the typed written names of the respective parties appearing at
the foot of the emails in question, were indeed intended to identify the
parties, amounted to data that was logically associated with data in the body of
the emails, and thus constituting legal electronic signatures, [paragraph 29]cite:Cachalia15_spring_forest_v_wilberry:
#+BEGIN_QUOTE
\textit{`There is no dispute regarding the reliability of the emails, the accuracy of the information communicated or the identities of the persons who appended their names to the emails. On the contrary, as I have found earlier, the emails clearly and unambiguously evinced an intention by the parties to cancel their agreements. It ill-behoves the respondent, which responded to clear questions by email itself, to now rely on the non-variation clauses to escape the consequences of its commitments made at the meeting on 25 February 2013 which were later confirmed by email.'}
#+END_QUOTE
Given that the SCA upheld the appeal, finding that the email cancellation of the
agreements in question was indeed valid, raises the important and difficult
question of whether courts of the Republic would hold a similar view in terms of
an agreement canceled via other electronic instant text messaging platforms and
social media, such as SMS[fn::Short Message Services.], WhatsApp, FaceBook
status updates, Twitter, etc...

** Can she cancel the contract? (5)

As per the provisions of [section 44(1)(a)]cite:rsa02_elect_comm_trans_act Kate
is entitled to cancel without reason nor penalty any transaction for the supply of
goods within seven days after the date of receipt of said goods. Additionally as
per the provisions of [section 20(1)]cite:rsa08_cpa Kate has the right to return
/defective/ goods, or as per [sections 19(5) and 20(2)(b)]cite:rsa08_cpa Kate
has the right to return goods which she did not have a reasonable opportunity to
inspect before delivery and was effectively denied the right to choose or
examine the goods as per [section 18]cite:rsa08_cpa. Moreover she is entitled to
a full refund [section 44(3)]cite:rsa02_elect_comm_trans_act and [section
20(5)]cite:rsa08_cpa, only being liable for direct costs of returning the
software as per the stipulations of [section
44(2)]cite:rsa02_elect_comm_trans_act and [section 20(6)]cite:rsa08_cpa.\\

As per the definitions of [section 53(1)(a)]cite:rsa08_cpa, Kate may argue that
the software is *`defective'* in that its performance is less than acceptable,
useful or practicabl,e than persons generally would be reasonably entitled to
expect in the circumstances. Moreover that the deployment of the software on her
machine could constitute *`failure'* [section 53(1)(b)]cite:rsa08_cpa, from the
inability of said software to perform in the intended manner or to the intended
effect. Additionally as per the provisions of [section 55(2)]cite:rsa08_cpa Kate
has the right to assume that the software was of good quality, reasonably
suitable for the purposes for which it was intended, in working order and free
of any defects.\\

With regards to when Kate can return the goods to the supplier for a refund, it
is interesting to note the discrepancy with regards to the *`cooling-off period*'
which is stipulated as *seven days* in the ECT[fn:: Electronic Communications
and Transactions Act No. 25 of 2002.] [section
44(1)(b)]cite:rsa02_elect_comm_trans_act and *six months* in the
CPA[fn::Consumer Protection Act No. 68 of 2008.] [section 56(2)]cite:rsa08_cpa,
which also stipulates provisions for the repair of defective goods. Kate would
be strongly advised to cancel the contract within 7 days.

* Discuss the following questions regarding the term permanent establishment (PE): [25]

** Describe what the term PE means. (5)

A *permanent establishment (PE)* is a fixed place of business through which the
business of an enterprise is wholly or partially carried on, [article
5(1)]cite:oecd17_model_tax, generally giving rise to income or VAT[fn::Value
added tax.] liability [article 7(1)]cite:oecd17_model_tax in a particular jurisdiction
resulting from the bilateral tax treaties negotiated for the treatment of
cross-border commerce. A PE is created in terms of a DTA[fn::Double taxation
agreement.], falling under the ambit of legislation to be administered by
an authorized person or commissioner as described in [schedule
1]cite:rsa97_sars_act, and details the requirements a non-resident enterprise
must meet under which profits generated through commercial actives in a foreign
state may subsequently be taxed in said foreign state. As per the provisions of
[section 1]cite:rsa62_income_tax, which directly refers to [article
5(2)]cite:oecd17_model_tax, examples of a PE include: a place of management; a
branch; an office; a factory; a workshop; a mine, an oil or gas well, a quarry
or any other place of extraction of natural resources; while a number of
exclusions are detailed in [article 5(4)]cite:oecd17_model_tax. A PE must satisfy the following prerequisites:
- *place-of-business test* - there must necessarily exist a distinct premises,
  equipment or machinery,
- *permanence test* - this must be established for a minimum prescribed
  duration, twelve months with respect to a building site or construction or
  installation project, [article 5(3)]cite:oecd17_model_tax, and
- *business-activities test* lastly personally of the enterprise or agents on
  their behalf, must conduct business activities at said place.

** Explain whether the following constitutes a PE on the Internet: a website; a server; a dependent agent. Refer to authoritative sources. (20)

Adopting an antiquated view one may traditionally describe a *website* as a
collection of software and electronic data messages or constructs of electronic
data, as per [section 1]cite:rsa02_elect_comm_trans_act. From such a description
one `could' argue that a website is intangible and as such cannot alone
constitute a /place of business/ and thus failing to qualify as a PE
[paragraph 124]cite:oecd17_model_tax. Whereas on
the other hand, a *server* through which the website is stored and accessible is
a piece of machinery or equipment having a physical location and may thus
constitute a /fixed place of business/ as per the commentary to article 5
[paragraph 123]cite:oecd17_model_tax, and in turn a PE.\\

Further distinction is required between the enterprises operating the server and
those that carry on business through the websites hosted on said servers.
Should an enterprise operating a website, also have at its own
disposal[fn::Through ownership or lease agreement.], use and operation of the
server hosting said website, then pending the other requirements the place where
that server is located could constitute a PE [paragraph
124]cite:oecd17_model_tax, provided it is fixed in that location for a
sufficient period of time [paragraph 125]cite:oecd17_model_tax.\\

In addition to the already mentioned reservations in establishing whether an
enterprise operating a website and/or server constitute a PE, one must also
consider whether:
- the business of an enterprise is wholly or partially carried on through such
  equipment needs to be examined on a case-by-case basis, [paragraphs 126 and 130]cite:oecd17_model_tax,
- the computer equipment is automated and that no personnel of that enterprise
  are required at the location [section 127]cite:oecd17_model_tax,
- no PE may exist where the computer equipment provides preparatory or
  auxiliary services, for example the advertising goods and services, supplying
  information, [paragraph 128]cite:oecd17_model_tax, unless these activities are
  themselves essential and significant core functions of said enterprise
  [129]cite:oecd17_model_tax,
- as per the provisions of [paragraph 131]cite:oecd17_model_tax
  ISPs[fn::Internet service providers.]  cannot constitute dependent agents as
  they do not have the authority to conclude -at least not regularly- contracts
  on behalf of enterprises, or they constitute independent agents and as such a
  PE may never arise in the case of ISPs,
- as per the provisions of [article 3]cite:oecd17_model_tax a website cannot
  constitute a dependent agent as it is not itself a person.

During the course of 2015, OECD[fn::Organization for Economic Co-operation and
Development] published the final version of their BEPS[fn::G20 Base Erosion and
Profit Shifting] Project cite:oecd15_action7, with the aim of addressing tax
avoidance strategies that exploit the use of commissionaire arrangements to
avoid [article 5(5)]cite:oecd17_model_tax, and reliance of specific activity
exemptions [article 5(4)]cite:oecd17_model_tax. As per the provisions of
[article 5(5)]cite:oecd17_model_tax a person acting on behalf of a foreign
enterprise, then that enterprise shall be deemed to be a PE within a
Contracting State, despite not necessarily having a /`fixed place-of-business'/,
provided said person has and habitually exercises authority to conclude
contracts, or plays the principle role leading to the conclusion of contracts
that are routinely concluded without material modification by the enterprise, in
respect of activities undertaken for that enterprise [paragraph
31]cite:oecd15_action7. Such a person constitutes a *dependent agent* and in
such a capacity a dependent agent can indeed constitute a PE,
cite:oecd18_additional_guidance.

* Bibliography                                                       :ignore:
\printbibliography
