* LaTeX Preamble                                                     :ignore:
#+TITLE: IPSP078 - Legal Aspects of Electronic Commerce
#+AUTHOR: Nyameko Lisa
#+DATE: 30 September 2018
#+SUBTITLE: Assignment 2: 724205

#+LATEX_HEADER: \usepackage[margin=0.80in]{geometry}
#+LATEX_HEADER: \usepackage[backend=biber, style=ieee, url=false]{biblatex}
#+LATEX_HEADER: \usepackage{float}
#+LATEX_HEADER: \usepackage[super,negative]{nth}
#+LATEX_HEADER: \usepackage[capitalise]{cleveref}
#+LATEX_HEADER: \usepackage{pst-node,transparent,ragged2e}
#+LATEX_HEADER: \addbibresource{/home/nlisa/.spacemacs.d/org-files/bibliography.bib}
#+LATEX_HEADER: \DeclareFieldFormat[inproceedings]{citetitle}{\textit{#1}}
#+LATEX_HEADER: \DeclareFieldFormat[inproceedings]{title}{\textit{#1}}
#+LATEX_HEADER: \DeclareFieldFormat[misc]{citetitle}{#1}
#+LATEX_HEADER: \DeclareFieldFormat[misc]{title}{#1}
#+LATEX_HEADER: \renewcommand*{\bibpagespunct}{%
#+LATEX_HEADER:   \ifentrytype{inproceedings}
#+LATEX_HEADER:     {\addspace}
#+LATEX_HEADER:     {\addcomma\space}}
#+LATEX_HEADER: \AtEveryCitekey{\ifuseauthor{}{\clearname{author}}}
#+LATEX_HEADER: \AtEveryBibitem{\ifuseauthor{}{\clearname{author}}}

#+OPTIONS: toc:nil
#+LATEX_HEADER: \SpecialCoor

# Institution
#+BEGIN_EXPORT latex
\addvspace{110pt}
\centering{
\pnode(0.5\textwidth,-0.5\textheight){thisCenter}
\rput(thisCenter){%\transparent{0.25}
\includegraphics[width=2.7in]{/home/nlisa/course/llb/wipo-unisa/UNISACoatofArms.eps}}}
#+END_EXPORT

#+LaTeX: \justifying
#+LaTeX: \addvspace{110pt}
* Declaration
  :PROPERTIES:
   :UNNUMBERED: t
  :END:
  I know that plagiarism is to use someone else’s work and pass it off as my own.\\
  I know that plagiarism is wrong.\\
  I confirm that this assignment is my own work.\\
  I have acknowledged in the bibliography accompanying the assignment all the sources that I have used.\\
  I have not directly copied without acknowledgement anything from the Internet or from any other source.\\
  I have indicated every quotation and citation in a footnote or bracket linked to that quotation.\\
  I have not allowed anyone else to copy my work and to pass it off as their own work.\\
  I understand that if any unacknowledged copying whatsoever appears in my assignment I will receive zero per cent for the assignment.\\
  I am aware of the UNISA policy on plagiarism and understand that disciplinary proceedings can be instituted against me by UNISA if I contravene this policy.\\
  I indicate my understanding and acceptance of this declaration by
  entering my name here under:
    - Name: *Nyameko Lisa* (Student Number: *7874-909-3*)

** NOTE
Please note that footnotes will be denoted as [fn::This is a footnote.] and will
appear at the bottom of the page.\\
References will be denoted by cite:rsa93_tm_act and will appear at the end of the document.
\newpage


* Question 1 [25]
cite:papadopoulus12_intro_cyberlaw,buys00_towards_ecomm_policy_sa,hamann14_direct_marketing_and_spam_via_ecomms,eiselen16_ecomm,gereda16_elec_comms_trans_act,pistorius16_copyright_law_it,pistorius16_domain_names_infringe_tm,un96_uncitral_model_law_ecomm,comesa10_model_law_on_e_trans,rsa00_green_paper_ecomm_sa,hipssa13_elec_trans_ecom_sadc_model_law,rsa12_elect_comm_trans_amend_bill,rsa12_ect_adr,rsa02_elect_comm_trans_act

The following discussions pertain to citetitle:Cachalia15_spring_forest_v_wilberry
cite:Cachalia15_spring_forest_v_wilberry,

** Briefly state the facts of the case. (5)

This case is an appeal from a decision of the high court, KwaZulu-Natal, Durban
(Judge Madondo) granting interim relief pendente lite following an urgent
application by Wilberry (Pty) Ltd t/a as Ecowash *the respondent*, against Spring
Forest Trading 599 CC *the appellant*, and Combined Motor Holdings Limited t/a
The Green Machine (CMH)[fn::Cited here as it has an interest in the relief
claimed, but is not party to the present appeal.].\\

The appeal concerns a series of emails purporting consensual written
cancellation of several agreements in which the applicant leased
MDU's[fn::Mobile Dispensing Units.] from the respondent, which the applicant
required for use in its mobile car wash business. The agreement included a
non-variation clause stipulating that changes to or cancellation of the
agreement would only be effective if reduced to writing and signed by both
parties, and afforded the appellant the right to promote, operate and lease out
the respondent's MDU's to third parties.\\

The appellant subsequently reneged on its rental obligations in terms of the
agreement, and after negotiations the parties had reached a verbal understanding
to cancel the standing agreements. The terms of the cancellation of the
agreements, were recorded in a series of email correspondences between the
respective representative(s) for the respondent Mr Nigel Keirby-Smith and those
for the appellant, Mr Gregory Stuart Hamilton and Mr Walter Burger. These
included the settlement of the rental payment in arrears owed by the appellant
and the return of the MDU's to the respondent.

** Identify and discuss the principle of law in the case. (5)

The appeal concerned a series of emails purporting to the consensual
cancellation of the written agreements. Stipulated within these written
agreements was that `consensual cancellation' to be effected *in writing and
signed by both parties*. As per the provisions of [sections 11, 12 and
13]cite:rsa02_elect_comm_trans_act, statutory regulations of the Republic
afford legal recognition to transactions concluded electronically via email. The
SCA[fn::Supreme Court of Appeals.] was required to consider whether the dispute
arising from the exchange of emails between the parties, indeed satisfy the
*writing* [section 12]cite:rsa02_elect_comm_trans_act and *signature* [section
13]cite:rsa02_elect_comm_trans_act requirements, thereby constituting legal
consensual cancellation.\\

The appellant settled the rental in arrears, but continued its car washing
operations at the locations of the rental agreements, arguing that it was
entitled to do so as the agreements between itself and the respondent had been
effectively canceled. The appellant then entered into subsequent agreements with
another entity to conduct the same operations. To which the respondent denied
the validity of the cancellations to the agreements, and sought interdictory
relief preventing the appellant from conducting said operations, protecting its
proprietary rights in it's MDU's pending the institution of breach of
agreement actions.\\

In the original action the HC[fn::(Durban) High Court.] found that the email
communication constituted inconclusive negotiations between the parties and did
not evince and intention to cancel the agreements, adding that the parties had
not explicitly specified that their agreements could be canceled via email.\\

The respondents argued that the emails did not comply with the requirements of
[section 13(1)]cite:rsa02_elect_comm_trans_act, lacking an endorsement of an
`advanced electronic signature'. Moreover, the respondent also argued that the
appellant cannot bring the emails into the ambit of the law as per the
provisions of [section 13(3)]cite:rsa02_elect_comm_trans_act, contending that
the emails pertain to oral negotiations about the agreement and hence cannot
constitute separate electronic transactions, nor were there any controls
implemented to identify the parties and indicate their approval.\\


** What was the court's decision regarding the issues raised? (5)

On appeal the SCA upheld that it was not in dispute whether the emails satisfied
the requirement that the cancellation need be `in writing', as per [section
12(a)]cite:rsa02_elect_comm_trans_act, of which statutory requirements are
satisfied if said correspondence is in the form of a `data message'. Instead the
SCA held that the real issue was whether the names of the parties at the foot of
their respective emails, indeed constituted signatures as per the provisions of
[section 13(1) and 13(3)]cite:rsa02_elect_comm_trans_act.\\

The SCA held that the stipulations for the requirement of an `advanced
electronic signature' [section 13(1)]cite:rsa02_elect_comm_trans_act did not
apply to the circumstances of this case, whereas however the less restrictive
requirements of an 'electronic signature' [section
13(3)]cite:rsa02_elect_comm_trans_act do indeed apply. Wherein it need only be
demonstrated that the requirement is indeed met if a method of electronic
signature used to identify a party and indicate their approval of the contained
information [section 13(3)(a)]cite:rsa02_elect_comm_trans_act, and that the method
was indeed `appropriately reliable' for the intended purposes of the information
communicated. In the SCA's analysis of [section 13(3)]cite:rsa02_elect_comm_trans_act, Justice
Cachali argued cite:Cachalia15_spring_forest_v_wilberry:
#+BEGIN_QUOTE
\textit{‘The respondent submits that the phrase: “Where the signature of a person is required by law” (emphasis added) in s 13(1) it should be interpreted not only to include formalities required by statute but must also incorporate instances where parties to an agreement impose their own formalities on a contract, as in this case. And, so the contention goes, because the parties required their signatures for the contracts to be cancelled the requirement could only be satisfied by the use of an advanced electronic signature as contemplated in s 13(1), which did not occur in this case.’}
#+END_QUOTE
** What is the impact of the case on the law? (5)

** What are the opinions of other authors regarding the principle discussed in the case? (5)

* Bibliography                                                       :ignore:
\printbibliography
