* LaTeX Preamble                                                     :ignore:
#+TITLE: IPSP033 - Essential Patent Law
#+AUTHOR: Nyameko Lisa
#+DATE: 22 September 2017
#+SUBTITLE: Assignment 02 - 690905

#+LATEX_HEADER: \usepackage[margin=0.80in]{geometry}
#+LATEX_HEADER: \usepackage[backend=biber, style=ieee]{biblatex}
#+LATEX_HEADER: \usepackage{float}
#+LATEX_HEADER: \usepackage[super,negative]{nth}
#+LATEX_HEADER: \usepackage[capitalise]{cleveref}
#+LATEX_HEADER: \usepackage{pst-node,transparent,ragged2e}
#+LATEX_HEADER: \addbibresource{/home/nuk3/course/training/csir/novellasers/bibliography/bibliography.bib}
#+LATEX_HEADER: \DeclareFieldFormat[inproceedings]{citetitle}{\textit{#1}}
#+LATEX_HEADER: \DeclareFieldFormat[inproceedings]{title}{\textit{#1}}
#+LATEX_HEADER: \DeclareFieldFormat[misc]{citetitle}{#1}
#+LATEX_HEADER: \DeclareFieldFormat[misc]{title}{#1}
#+LATEX_HEADER: \renewcommand*{\bibpagespunct}{%
#+LATEX_HEADER:   \ifentrytype{inproceedings}
#+LATEX_HEADER:     {\addspace}
#+LATEX_HEADER:     {\addcomma\space}}
#+LATEX_HEADER: \AtEveryCitekey{\ifuseauthor{}{\clearname{author}}}
#+LATEX_HEADER: \AtEveryBibitem{\ifuseauthor{}{\clearname{author}}}

#+LATEX_HEADER: \PassOptionsToPackage{hyperref,x11names}{xcolor}
#+LATEX_HEADER: \hypersetup{colorlinks=true,citecolor=blue,filecolor=cyan,linkcolor=black,urlcolor=blue}

#+OPTIONS: toc:nil
#+LATEX_HEADER: \SpecialCoor

# Institution
#+BEGIN_EXPORT latex
\addvspace{110pt}
\centering{
\pnode(0.5\textwidth,-0.5\textheight){thisCenter}
\rput(thisCenter){%\transparent{0.25}
\includegraphics[width=2.7in]{/home/nuk3/course/llb/wipo-unisa/UNISACoatofArms.eps}}}
#+END_EXPORT

#+LaTeX: \justifying
#+LaTeX: \addvspace{110pt}
* Declaration
  :PROPERTIES:
   :UNNUMBERED: t
  :END:
  I know that plagiarism is to use someone else’s work and pass it off as my own.\\
  I know that plagiarism is wrong.\\
  I confirm that this assignment is my own work.\\
  I have acknowledged in the bibliography accompanying the assignment all the sources that I have used.\\
  I have not directly copied without acknowledgement anything from the Internet or from any other source.\\
  I have indicated every quotation and citation in a footnote or bracket linked to that quotation.\\
  I have not allowed anyone else to copy my work and to pass it off as their own work.\\
  I understand that if any unacknowledged copying whatsoever appears in my assignment I will receive zero per cent for the assignment.\\
  I am aware of the UNISA policy on plagiarism and understand that disciplinary proceedings can be instituted against me by UNISA if I contravene this policy.\\
  I indicate my understanding and acceptance of this declaration by
  entering my name hereunder:
    - Name: *Nyameko Lisa* (Student Number: *7874-909-3*)

** NOTE
Please note that footnotes will be denoted as [fn::This is a footnote.] and will
appear at the bottom of the page.\\
References will be denoted by cite:rsa78_patents_act and will appear at the end of the document.
\newpage

* Advise Dr Genius whether Dr De Ville is infringing his patent rights.

As per [section 45(1)]cite:rsa78_patents_act and [Article 28(1)]cite:wto17_trips, Dr Genius' patent grants him monopoly and exclusive rights to exclude others from making /(manufacture, fabrication and production of)/, using /(incorporating into motor vehicles, and possession with intent to sell)/, exercising /(making use of and incorporating into motor vehicles)/, disposing of (distributing, marketing and selling), or offering to dispose of /(offering to distribute, market or sell)/ his patented invention.\\

Therefore anyone who performs any one of these acts, except where specifically qualified by a statutory provision such as a license [section 53]cite:rsa78_patents_act and [Article 28(2)]cite:wto17_trips, without consent of patentee, infringes the patent, and the patentee is entitled to enforce his patent rights by instituting proceedings against such an infringer, [section 65(1)]cite:rsa78_patents_act and [Article 41(1)]cite:wto17_trips.\\

Traditionally, in manufacturing and marketing a similar device which _embodies all of the essential features or characteristics_ of the patent claim, Dr Genius would have been able to seek remedies against Dr De Ville for infringement as per the /`doctrine of pith-and-marrow'/, as worded in citetitle:steyn60_frank_hirch_v_rodi_wien cite:steyn60_frank_hirch_v_rodi_wien.\\

The fact that Dr De Ville has manufactured and marketed a device that may have a similar result or similar fundamental operation to that of Dr Genius, has no bearing on infringement. For any remedy against infringement, Dr Genius will need to demonstrate that *all* the essential components or integers that are present in his patent claim, are indeed present in the allegedly infringing article, collectively acting in the manner claimed.\\

In South African law this is referred to as the /`doctrine of purposive construction'/, and was particularly well articulated in citetitle:corbett87_rauben_kreepy_krauly cite:corbett87_rauben_kreepy_krauly, where the court held that the swimming pool cleaning device of the respondent did not infringe appellants' patent where one of the essential integers of a claim in the appellants' patent was not present in the respondents' device, even though the two devices achieve the same result and have the same fundamental operation.\\

Should Dr Genius be able to demonstrate that Dr De Ville's device comprises all the essential or integral components of his patent, the manner claimed, then Dr Genius may be see relief in the form of and interdict or injunction [section 65(3)(a)]cite:rsa78_patents_act and [Article 44]cite:wto17_trips, delivery of infringing product or articles of which infringing product forms an inseparable part [section 65(3)(b)]cite:rsa78_patents_act, damages [section 65(3)(c)]cite:rsa78_patents_act and [Article 45]cite:wto17_trips, through royalties in lieu of damages [section 65(6)]cite:rsa78_patents_act, or disposal or destruction of the infringing articles, outside the channels of commerce and without compensation [Article 46]cite:wto17_trips.

* Bibliography                                                       :ignore:
\printbibliography

#  LocalWords:  patentable infringer
