* LaTeX Preamble                                                     :ignore:
#+TITLE: IPSP033 - Essential Patent Law
#+AUTHOR: Nyameko Lisa
#+DATE: 21 August 2017
#+SUBTITLE: Assignment 01 - 721244

#+LATEX_HEADER: \usepackage[margin=0.80in]{geometry}
#+LATEX_HEADER: \usepackage[backend=biber, style=ieee]{biblatex}
#+LATEX_HEADER: \usepackage{float}
#+LATEX_HEADER: \usepackage[super,negative]{nth}
#+LATEX_HEADER: \usepackage[capitalise]{cleveref}
#+LATEX_HEADER: \usepackage{pst-node,transparent,ragged2e}
#+LATEX_HEADER: \addbibresource{/home/nuk3/course/training/csir/novellasers/bibliography/bibliography.bib}
#+LATEX_HEADER: \DeclareFieldFormat[inproceedings]{citetitle}{\textit{#1}}
#+LATEX_HEADER: \DeclareFieldFormat[inproceedings]{title}{\textit{#1}}
#+LATEX_HEADER: \DeclareFieldFormat[misc]{citetitle}{#1}
#+LATEX_HEADER: \DeclareFieldFormat[misc]{title}{#1}
#+LATEX_HEADER: \renewcommand*{\bibpagespunct}{%
#+LATEX_HEADER:   \ifentrytype{inproceedings}
#+LATEX_HEADER:     {\addspace}
#+LATEX_HEADER:     {\addcomma\space}}
#+LATEX_HEADER: \AtEveryCitekey{\ifuseauthor{}{\clearname{author}}}
#+LATEX_HEADER: \AtEveryBibitem{\ifuseauthor{}{\clearname{author}}}

#+OPTIONS: toc:nil
#+LATEX_HEADER: \SpecialCoor

# Institution
#+BEGIN_EXPORT latex
\addvspace{110pt}
\centering{
\pnode(0.5\textwidth,-0.5\textheight){thisCenter}
\rput(thisCenter){%\transparent{0.25}
\includegraphics[width=2.7in]{/home/nuk3/course/llb/wipo-unisa/UNISACoatofArms.eps}}}
#+END_EXPORT

#+LaTeX: \justifying
#+LaTeX: \addvspace{110pt}
* Declaration
  :PROPERTIES:
   :UNNUMBERED: t
  :END:
  I know that plagiarism is to use someone else’s work and pass it off as my own.\\
  I know that plagiarism is wrong.\\
  I confirm that this assignment is my own work.\\
  I have acknowledged in the bibliography accompanying the assignment all the sources that I have used.\\
  I have not directly copied without acknowledgement anything from the Internet or from any other source.\\
  I have indicated every quotation and citation in a footnote or bracket linked to that quotation.\\
  I have not allowed anyone else to copy my work and to pass it off as their own work.\\
  I understand that if any unacknowledged copying whatsoever appears in my assignment I will receive zero per cent for the assignment.\\
  I am aware of the UNISA policy on plagiarism and understand that disciplinary proceedings can be instituted against me by UNISA if I contravene this policy.\\
  I indicate my understanding and acceptance of this declaration by
  entering my name hereunder:
    - Name: *Nyameko Lisa* (Student Number: *7874-909-3*)

** NOTE
Please note that footnotes will be denoted as [fn::This is a footnote.] and will
appear at the bottom of the page.\\
References will be denoted by cite:rsa78_patents_act and will appear at the end of the document.
\newpage

* Discuss whether the device qualifies as an invention for the purposes of patent protection.
\label{sec:invention}

As per the definition specified in [section 2]cite:rsa78_patents_act and [Article 27(1)]cite:wto17_trips, Dr Genius' device need satisfy the provisions for a patent to be granted under [section 25]cite:rsa78_patents_act, wherein subsection (1) of that section of the Act stipulates that a patent may be granted for a *new* invention, involving an *inventive step* and has application to trade or industry. The novelty and inventiveness requirements will be addressed in answers ref:sec:novel and ref:sec:inventiveness.\\

The content of the concept ``patentable subject-matter' is usually established in the negative sense by statue, i.e. inventions explicitly `excluded' from qualification for the purposes of patent protection. Dr Genius' device neither falls into any of the categories listed under [subsections (2) and (3) of section 25]cite:rsa78_patents_act, nor those articulated in [Article 27(2) and Article 27(3)]cite:wto17_trips.\\

However it must be noted that without specifications and operating details of device, it is impossible to say whether or not converting leaded petrol engines into engines that can also use unleaded petrol, has any adverse effects on the environment. Should this be the case, then as per [Article 27(2)]cite:wto17_trips, the device would be excluded as a patentable invention, given that it circumvents measures put in place to /``...avoid serious prejudice to the environment''/.

* Discuss whether the device meets the novelty requirement.
\label{sec:novel}

For the discussions that follow, /`priority date'/ will be understood as it is
described in [section 33]cite:rsa78_patents_act, to be the date on which the
application for the patent was filed with the receiving Office. A similar
definition will be used, regarding international patents pertaining to Paris
Convention member states as stipulated in [Article 29(1)]cite:wto17_trips,
[Articles 8 and 11]cite:wipo70_pct and [Article 4]cite:wipo83_paris_conve_protect_ip. Furthermore identifying whether or not an invention is new, or involves an inventive step is primarily in the domain of establishing infringement or revocation of a patent or license.\\

As per the provisions of [section 25(5)]cite:rsa78_patents_act, Dr Genius'
device will be deemed to be new provided it does not form part of the /`state of
the art'/ immediately before it's priority date. Where as per the provisions of
[subsections (6), (7) and (8) of section 25]cite:rsa78_patents_act respectively,
the /state of the art/ includes all matter:
- [subsection (6)], related to the device that has been made available to the public within the Republic or elsewhere, by written, or by oral, or through use or by any other means,
- [subsection (7)], given a preceding priority date, a patent application open to public inspection, and
- [subsection (8)], inventions used secretly and on a commercial scale.

Similar wording is stipulated in [Article 33(2)]cite:wipo70_pct, with a detailed description of the reference to prior art given in [Rule 33]cite:wipo70_pct_reg, wherein the International Search Authority is responsible in establishing novelty of the invention.\\

Moreover as per the provisions of [Article 25(1)]cite:wto17_trips, Dr Genius' device will be considered new or original, provided that it is significantly different from existing designs or combinations thereof. Such an example exists in South African case law, citetitle:davis42_levin_v_numplates cite:davis42_levin_v_numplates, where it was argued that /"Any previous publication, in order to avail the defendant, must be of something practically identical with the plaintiff's plate: there must be no substantial difference between them."/

* Discuss whether the device meets the inventiveness requirement.
\label{sec:inventiveness}

As per the provisions of [section 25(10)]cite:rsa78_patents_act, Dr Genius' device may be considered to involve an inventive step if it is *not obvious* to a *person skilled in the art* having regards to any prior art immediately preceding the priority date of his invention, when *only* considering subject matter made available to the public, within the Republic or elsewhere, by written, oral, use or any other means, as stipulated in [section 25(6)]cite:rsa78_patents_act.\\

In establishing whether the device satisfies the inventiveness requirement, /state of the art/ of a `smaller' scope is applied than the test for novelty, in that all other knowledge in the public domain is _disregarded_, be it patent applications open to public inspection, [section 25(7)]cite:rsa78_patents_act, or proprietary commercialised secret inventions [section 25(8)]cite:rsa78_patents_act. Such an example exists in South African case law, citetitle:davis42_levin_v_numplates cite:davis42_levin_v_numplates, where it was argued that /``Subject matter must be measured by common knowledge. Public knowledge must be discarded absolutely. No text-books have been produced by the defendant to show that the invention was common knowledge. A witness cannot be asked, is the thing new, and it is obvious''/.\\

With regards to the international instruments, [Article 27(1)]cite:wto17_trips
deems the notion of inventiveness to be synonymous with the term
``non-obvious''. Similar wording is used in [Article 33(3)]cite:wipo70_pct,
which stipulates that the Dr Genius' device will be considered to involve an
inventive step if it is not, at the prescribed relevant date, obvious to a
person skilled in the art. Where the concept of prior art is as described in
[Rules 64 and 65]cite:wipo70_pct_reg of the PCT Regulations.
* Bibliography                                                       :ignore:
\printbibliography

#  LocalWords:  patentable
