* LaTeX Preamble                                                     :ignore:
#+TITLE: IPSP033 - Essential Patent Law
#+AUTHOR: Nyameko Lisa
#+DATE: 27 October 2017
#+SUBTITLE: Assignment 03 - Exam

#+LATEX_HEADER: \usepackage[margin=0.80in]{geometry}
#+LATEX_HEADER: \usepackage[backend=biber, style=ieee]{biblatex}
#+LATEX_HEADER: \usepackage{float}
#+LATEX_HEADER: \usepackage[super,negative]{nth}
#+LATEX_HEADER: \usepackage[capitalise]{cleveref}
#+LATEX_HEADER: \usepackage{pst-node,transparent,ragged2e}
#+LATEX_HEADER: \addbibresource{/home/nuk3/course/training/csir/novellasers/bibliography/bibliography.bib}
#+LATEX_HEADER: \DeclareFieldFormat[inproceedings]{citetitle}{\textit{#1}}
#+LATEX_HEADER: \DeclareFieldFormat[inproceedings]{title}{\textit{#1}}
#+LATEX_HEADER: \DeclareFieldFormat[misc]{citetitle}{#1}
#+LATEX_HEADER: \DeclareFieldFormat[misc]{title}{#1}
#+LATEX_HEADER: \renewcommand*{\bibpagespunct}{%
#+LATEX_HEADER:   \ifentrytype{inproceedings}
#+LATEX_HEADER:     {\addspace}
#+LATEX_HEADER:     {\addcomma\space}}
#+LATEX_HEADER: \AtEveryCitekey{\ifuseauthor{}{\clearname{author}}}
#+LATEX_HEADER: \AtEveryBibitem{\ifuseauthor{}{\clearname{author}}}

#+LATEX_HEADER: \PassOptionsToPackage{hyperref,x11names}{xcolor}
#+LATEX_HEADER: \hypersetup{colorlinks=true,citecolor=blue,filecolor=cyan,linkcolor=black,urlcolor=blue}

#+OPTIONS: toc:nil
#+LATEX_HEADER: \SpecialCoor

# Institution
#+BEGIN_EXPORT latex
\addvspace{110pt}
\centering{
\pnode(0.5\textwidth,-0.5\textheight){thisCenter}
\rput(thisCenter){%\transparent{0.25}
\includegraphics[width=2.7in]{/home/nuk3/course/llb/wipo-unisa/UNISACoatofArms.eps}}}
#+END_EXPORT

#+LaTeX: \justifying
#+LaTeX: \addvspace{110pt}
* Declaration
  :PROPERTIES:
   :UNNUMBERED: t
  :END:
  I know that plagiarism is to use someone else’s work and pass it off as my own.\\
  I know that plagiarism is wrong.\\
  I confirm that this assignment is my own work.\\
  I have acknowledged in the bibliography accompanying the assignment all the sources that I have used.\\
  I have not directly copied without acknowledgement anything from the Internet or from any other source.\\
  I have indicated every quotation and citation in a footnote or bracket linked to that quotation.\\
  I have not allowed anyone else to copy my work and to pass it off as their own work.\\
  I understand that if any unacknowledged copying whatsoever appears in my assignment I will receive zero per cent for the assignment.\\
  I am aware of the UNISA policy on plagiarism and understand that disciplinary proceedings can be instituted against me by UNISA if I contravene this policy.\\
  I indicate my understanding and acceptance of this declaration by
  entering my name hereunder:
    - Name: *Nyameko Lisa* (Student Number: *7874-909-3*)

** NOTE
Please note that footnotes will be denoted as [fn::This is a footnote.] and will
appear at the bottom of the page.\\
References will be denoted by cite:rsa78_patents_act and will appear at the end of the document.
\newpage

* Advise Amos whether any of Bongani's argument have merit, and whether he can succeed with proceedings against him [50] (\tilde 3pg)
For the discussions that follow, /`priority date'/ will be understood as it is described in [section 33]cite:rsa78_patents_act, to
be the date on which the application for the patent was filed with the receiving Office. A similar definition will be used,
regarding international patents pertaining to Paris Convention member states as stipulated in [Article 29(1)]cite:wto17_trips,
[Articles 8 and 11]cite:wipo70_pct and [Article 4]cite:wipo83_paris_conve_protect_ip. Furthermore identifying whether or not an
invention is new, or involves an inventive step is primarily in the domain of establishing infringement or revocation of a patent
or license.\\

** On the merits of Bongani's arguments
*** The patent 161/09 is invalid for lack of patentable subject matter and lack of novelty
Should Amos wish to pursue infringement proceedings against Bongani, he should be made aware that Bongani may counterclaim
[section 65(4)]cite:rsa78_patents_act, for the revocation of Amos' patent as per the provisions of [section
61(1)(c)]cite:rsa78_patents_act. As per the definition specified in [section 2]cite:rsa78_patents_act and [Article
27(1)]cite:wto17_trips, Amos' composition need satisfy the provisions for a patent to be granted under [section
25]cite:rsa78_patents_act, wherein subsection (1) of that section of the Act stipulates that a patent may be granted for a *new*
invention, involving an *inventive step* and has application to trade or industry. Moreover the content of the concept
``patentable subject-matter' is usually established in the negative sense by statue, i.e. inventions explicitly `excluded' from
qualification for the purposes of patent protection. Amos' composition neither falls into any of the categories listed under
[subsections (2), (3) and (4) of section 25]cite:rsa78_patents_act, nor those articulated in [Article 27(2) and Article
27(3)]cite:wto17_trips.\\

As per the provisions of [section 25(9)]cite:rsa78_patents_act, even though the ingredient was used fairly generally prior to the
date in respect of which Amos' patent application was filed, given that the use of the ingredient for treating AIDS was not
known prior to said date, revocation of the patent cannot be argued on these grounds as even though the composition does indeed
form part of the state of the art prior to the date of application, the *use* of the composition in the specified manner does not
form part of the state of the art at that date.\\

As per the provisions of [section 25(5)]cite:rsa78_patents_act, Amos' composition will be deemed to be new provided it does not
form part of the /`state of the art'/ immediately before it's priority date. Where as per the provisions of [subsections (6), (7)
and (8) of section 25]cite:rsa78_patents_act respectively, the /state of the art/ includes all matter:
- [subsection (6)], related to the device that has been made available to the public within the Republic or elsewhere, by written, or by oral, or through use or by any other means,
- [subsection (7)], given a preceding priority date, a patent application open to public inspection, and
- [subsection (8)], inventions used secretly and on a commercial scale.

Similar wording is stipulated in [Article 33(2)]cite:wipo70_pct, with a detailed description of the reference to prior art given in [Rule 33]cite:wipo70_pct_reg, wherein the International Search Authority is responsible in establishing novelty of the invention.\\

As per the provisions of [section 25(10)]cite:rsa78_patents_act, Amos' composition may be considered to involve an inventive step
if it is *not obvious* to a *person skilled in the art* having regards to any prior art immediately preceding the priority date of
his invention, when *only* considering subject matter made available to the public, within the Republic or elsewhere, by written,
oral, use or any other means, as stipulated in [section 25(6)]cite:rsa78_patents_act. With regards to the international
instruments, [Article 27(1)]cite:wto17_trips deems the notion of inventiveness to be synonymous with the term ``non-obvious''.
Similar wording is used in [Article 33(3)]cite:wipo70_pct, which stipulates that the Amos' composition will be considered to
involve an inventive step if it is not, at the prescribed relevant date, obvious to a person skilled in the art. Where the concept
of prior art is as described in [Rules 64 and 65]cite:wipo70_pct_reg of the PCT Regulations, as demonstrated above.\\

There are therefore no merits to Bongani's arguments in this sense. However it must be noted that without specifications and
operating details of device, it is impossible to say whether or not the composition for treating AIDS in humans has any adverse
effects on the environment. Should this be the case, then as per [Article 27(2)]cite:wto17_trips, the composition may be excluded
as a patentable invention, given that it circumvents measures put in place to /``...avoid serious prejudice to the environment''/
and Bongani may be able to argue for the revocation of Amos' patent. In doing so however, Bongani would also prejudice his own
application.

*** The experimental work carried out by Bongani does not constitute infringement of the patent in terms of [section 45]cite:rsa78_patents_act
This demonstrates misinterpretation of the legislation by Bongani. As per the provisions of [section 45(1)]cite:rsa78_patents_act
and [Article 28(1)(a)]cite:wto17_trips, the experimental work undertaken by Bongani amounts to either making, using, or exercising
of the composition for which Amos has a patent for, granting him (Amos) the exclusive right to conduct any of the said activities,
and hence Bongani's experimental work does in deed constitute infringement.\\

Therefore anyone who performs any one of these acts, except where specifically qualified by a statutory provision such as a license [section 53]cite:rsa78_patents_act and [Article 28(2)]cite:wto17_trips, without consent of patentee, infringes the patent, and the patentee is entitled to enforce his patent rights by instituting proceedings against such an infringer, [section 65(1)]cite:rsa78_patents_act and [Article 41(1)]cite:wto17_trips.\\

Traditionally, Bongani experimenting with a substance composed of a similar
composition which _embodies all of the essential features or characteristics_ of
Amos' patent claim, he (Amos) would have been able to seek remedies against Bongani for infringement as per the /`doctrine of pith-and-marrow'/, as worded in citetitle:steyn60_frank_hirch_v_rodi_wien cite:steyn60_frank_hirch_v_rodi_wien.\\

*** Even if such experimental work did constitute infringement, Amos did not suffer any damage as a result of said infringement
Should Amos be able to demonstrate that Bongani's composition comprises all the
essential or integral components of his patent, in the manner claimed, even if
Amos did not suffer any
damages [section 65(3)(c)]cite:rsa78_patents_act and [Article
45]cite:wto17_trips, nor if Amos is unable to seek royalties in lieu of damages [section
65(6)]cite:rsa78_patents_act, Amos may still seek relief in the form
of
\begin{enumerate}
\item an interdict or injunction [section 65(3)(a)]\cite{rsa78_patents_act} and
[Article 44]\cite{wto17_trips},
\item delivery of infringing product or articles of which infringing product
forms an inseparable part [section 65(3)(b)]\cite{rsa78_patents_act}, or
\item disposal or destruction of the infringing articles, outside the channels of commerce and without compensation [Article 46]\cite{wto17_trips}.
\end{enumerate}
*** Since Bongani does not intent to commence selling the composition until after Amos' patent has lapsed, Amos has no cause of action against him
Once Amos' patent has expired no action for infringement may be brought against
Bongani, however possession of experimental composition prior to the date on
which the patent has lapsed, still amounts to infringement, in that Bongani is
exploiting the exclusive rights of Amos to make, use, exercises or dispose of
the composition, [section 45(1)]cite:rsa78_patents_act
and [Article 28(1)(a)]cite:wto17_trips.
** Whether Amos will succeed with proceedings against Bongani for
Amos may submit an application to the High Court in the prescribed manner
[section 65(2)]cite:rsa78_patents_act requesting an interim
interdict, requiring Bongani to immediately cease and desist from making, using or
exercising the composition in his experiments. This can then be escalated to a
full trial where Amos can seek a final interdict by way of action or application
should there be no material factual dispute between Bongani and Amos, [section
65(3)(a)]cite:rsa78_patents_act. Amos is likely to succeed in this action, as it
will be trivial to demonstrate that Bongani is indeed currently exploiting Amos'
exclusive rights granted by his patent, to make, use or exercises the
composition, moreover it is clear that Bongani also intends to dispose or, or
offer to dispose of by way of sale, the infringing composition.\\

Amos may seek delivery up of the infringing experimental materials and articles
[section 65(3)(b)]cite:rsa78_patents_act, arguing that this will enhance the
efficacy of the interdict, in that Bongani will be deprived of a means to
perform said acts of infringement. Moreover given that Amos' patent grants him
the exclusive right to dispose of or offer to dispose of[fn::I.e. sell.]and
enjoy the whole profit and advantage accruing by reason of his composition
[section 45(1)]cite:rsa78_patents_act, he can request that the court also order
delivery up of the registration certificate issued to Bongani in terms of
cite:rsa65_medicines_related_substances_act. Here Amos could argue that the
registration certificate is a product of which the infringing product form an
inseparable part[fn::Bongani has no right to sell the composition, the
certificate grants him this right, hence Amos is entitled to request delivery up
of said certificate.]. In light of the above arguments Amos is indeed likely to
succeed in such actions.\\

Provided that Bongani has not yet commenced with the marketing and sale of the
infringing composition, he will be unable to demonstrate actual or prospective loss[fn:: In the form of profit or sales.] nor
dilution of goodwill through unfair competition [Articles 3(1) and
3(2)]cite:wipo96_model_provi_unfair_comp, and hence will not likely
succeed in seeking relief in the form of damages [section
65(3)(c)]cite:rsa78_patents_act. Moreover he'd also be required to demonstrate
that on the date of infringement Bongani was indeed aware of Amos' patent
[section 66(1)]cite:rsa78_patents_act.
* Advise XYZ (Pty) Ltd whether [50]:
** ABC Inc is likely to succeed with such proceedings, and whether they will obtain all relief claimed for
** XYZ (Pty) Ltd is likely to succeed with its application for a compulsory license
* Bibliography                                                       :ignore:
\printbibliography

#  LocalWords:  patentable infringer Bongani's Bongani XYZ patentee
