* LaTeX Preamble                                                     :ignore:
#+TITLE: IPSP044 - Essential Trade Mark Law
#+AUTHOR: Nyameko Lisa
#+DATE: 27 October 2017
#+SUBTITLE: Assignment 03 - 788684

#+LATEX_HEADER: \usepackage[margin=0.80in]{geometry}
#+LATEX_HEADER: \usepackage[backend=biber, style=ieee]{biblatex}
#+LATEX_HEADER: \usepackage{float}
#+LATEX_HEADER: \usepackage[super,negative]{nth}
#+LATEX_HEADER: \usepackage[capitalise]{cleveref}
#+LATEX_HEADER: \usepackage{pst-node,transparent,ragged2e}
#+LATEX_HEADER: \addbibresource{/home/nuk3/course/training/csir/novellasers/bibliography/bibliography.bib}
#+LATEX_HEADER: \DeclareFieldFormat[inproceedings]{citetitle}{\textit{#1}}
#+LATEX_HEADER: \DeclareFieldFormat[inproceedings]{title}{\textit{#1}}
#+LATEX_HEADER: \DeclareFieldFormat[misc]{citetitle}{#1}
#+LATEX_HEADER: \DeclareFieldFormat[misc]{title}{#1}
#+LATEX_HEADER: \renewcommand*{\bibpagespunct}{%
#+LATEX_HEADER:   \ifentrytype{inproceedings}
#+LATEX_HEADER:     {\addspace}
#+LATEX_HEADER:     {\addcomma\space}}
#+LATEX_HEADER: \AtEveryCitekey{\ifuseauthor{}{\clearname{author}}}
#+LATEX_HEADER: \AtEveryBibitem{\ifuseauthor{}{\clearname{author}}}
#+LATEX_HEADER: \renewcommand\thesection{(\alph{section})}

#+LATEX_HEADER: \PassOptionsToPackage{hyperref,x11names}{xcolor}
#+LATEX_HEADER: \hypersetup{colorlinks=true,citecolor=blue,filecolor=cyan,linkcolor=black,urlcolor=blue}

#+OPTIONS: toc:nil
#+LATEX_HEADER: \SpecialCoor

# Institution
#+BEGIN_EXPORT latex
\addvspace{110pt}
\centering{
\pnode(0.5\textwidth,-0.5\textheight){thisCenter}
\rput(thisCenter){%\transparent{0.25}
\includegraphics[width=2.7in]{/home/nuk3/course/llb/wipo-unisa/UNISACoatofArms.eps}}}
#+END_EXPORT

#+LaTeX: \justifying
#+LaTeX: \addvspace{110pt}
* Declaration
  :PROPERTIES:
   :UNNUMBERED: t
  :END:
  I know that plagiarism is to use someone else’s work and pass it off as my own.\\
  I know that plagiarism is wrong.\\
  I confirm that this assignment is my own work.\\
  I have acknowledged in the bibliography accompanying the assignment all the sources that I have used.\\
  I have not directly copied without acknowledgement anything from the Internet or from any other source.\\
  I have indicated every quotation and citation in a footnote or bracket linked to that quotation.\\
  I have not allowed anyone else to copy my work and to pass it off as their own work.\\
  I understand that if any unacknowledged copying whatsoever appears in my assignment I will receive zero per cent for the assignment.\\
  I am aware of the UNISA policy on plagiarism and understand that disciplinary proceedings can be instituted against me by UNISA if I contravene this policy.\\
  I indicate my understanding and acceptance of this declaration by
  entering my name hereunder:
    - Name: *Nyameko Lisa* (Student Number: *7874-909-3*)

** NOTE
Please note that footnotes will be denoted as [fn::This is a footnote.] and will
appear at the bottom of the page.\\
References will be denoted by cite:rsa78_patents_act and will appear at the end of the document.
\newpage

* Resources

cite:wto17_trips

cite:nienaber02_arjo_v_idem,clayden55_int_tobaco_v_united_tobaco,joffe94_fifa_bartlett,wipo57_ncl,vivier2000_cadbury_v_beacon,harms01_cowbell_v_ics,moseneke06_laugh_v_sab,corbett97_mcd_v_joburgers,corbett84_plascon_v_riebeeck,harms07_verimark_v_bmw,davis42_levin_v_numplates

* Advise Aroma Company whether the mark qualifies for registration as a trade mark. [25]
As per the definitions of [section 2(1)]cite:rsa93_tm_act and given that the
Republic is a Paris Convention Member State, [article 15(1)]cite:wto17_trips,
[article 1(2)]cite:wipo83_paris_conve_protect_ip, it follows that /`TROPIC
GLOW'/ will be understood to be a *mark*, in that it is either a name or sign
capable of being represented graphically. Moreover it constitutes a *trade
mark*, as it has been proposed by Aroma Company, in relation to distinguishing
their trade or use from other goods or services connected in the course of trade
regarding /`soaps, perfumery, essential oils and cosmetics'/. Therefore it
follows as per [section 9(1)]cite:rsa93_tm_act, that TROPIC GLOW qualifies for
registration as trade mark, subject to limitations, in relation to use within
those limitations, and thus the unregistrability conditions of the
provisions of [paragraphs (1), (4), (5), (8), (9), (10) or (11) of section 10]cite:rsa93_tm_act,
cannot be applied.\\

As per [section 2(4)]cite:rsa93_tm_act, /`use'/ or /`proposed use'/ shall be
construed as the use of a visual representation of the mark [section
2(2)(a)]cite:rsa93_tm_act, as pertaining to physical form or other relation in
terms of goods[section 2(3)(a)]cite:rsa93_tm_act, or as pertaining to the use
thereof in any relation to the performance of any services[fn::Also referred to
as service marks, [article 1(2)]cite:wipo83_paris_conve_protect_ip] [section
2(3)(b)]cite:rsa93_tm_act. Provided that no others claim priority to the TROPIC
GLOW mark at the  of application for registration, then as per [section
9(2)]cite:rsa93_tm_act, TROPIC GLOW shall be considered to be capable of
distinguishing within the meaning described above. Thus also negating the
unregistrability conditions of the provisions of [paragraphs (2), (3) or (6) of section 10]cite:rsa93_tm_act\\

As per [section 11(1)]cite:rsa93_tm_act, the TROPIC GLOW mark is proposed to be
registered in respect of goods falling in a particular class, namely class 3,
hence [section 10(4)]cite:rsa93_tm_act cannot be applied.
Moreover TROPIC GLOW does not include or consist of the name or representation
of a person [section 12]cite:rsa93_tm_act, hence there would be no need to furnish the
registrar with additional legal consent from any parties. There would be no need
for the registrar to impose honest concurrent use conditions and limitations
[section 14(1)]cite:rsa93_tm_act, as the mark TROPIC GLOW does not offend
against the provisions of [paragraphs (6), (14), (15) or (17) of section
10]cite:rsa93_tm_act. It has already been demonstrated that TROPIC GLOW contains
matter which is indeed capable of distinguishing within the meaning of [section
9]cite:rsa93_tm_act, hence registration shall be subject to neither disclaimer
nor memorandum [section 15]cite:rsa93_tm_act, and Aroma Company shall not be
required to disclaim any right to the exclusive use of all or any portion of
TROPIC GLOW, [section 15(a)]cite:rsa93_tm_act.\\

Provided that TROPIC GLOW does not inherently [section 10(12)]cite:rsa93_tm_act
or from the manner of its use [section 10(13)]cite:rsa93_tm_act , likely to
deceive, cause confusion or offend any class of person, it cannot be deemed
unregistrable. Moreover provided that TROPIC GLOW does not constitute an
identical or similar trade mark registration [section 10(14)]cite:rsa93_tm_act
or prior application [paragraphs (15) and (16) of section 10]cite:rsa93_tm_act,
where use of TROPIC GLOW would likely amount to deceit or confusion in relation
to the goods and services of a different proprietor or applicant, respectively,
without their consent; the registrar cannot refuse registration on those
grounds. Lastly provided TROPIC GLOW does not constitute an identical or similar
mark already registered and well known in the Republic, [section
10(17)]cite:rsa93_tm_act, the registration cannot be refused on the grounds of
unfair competition through the dilution of good will.

* Advise Aroma Company whether any of these prior applications/registrations will present an obstacle to the registration of its marks. [25]
10(6),(14),(15),(17)
14 honest
15 disclaimer

* What must Aroma Company establish in order to succeed with any infringement action against Beaver Company? [25]

* Advise Aroma Company whether any formalities are necessary and/or advisable to protect its trade mark rights. [25]

* Bibliography                                                       :ignore:
\printbibliography

#  LocalWords:  patentable infringer unregistrability unregistrable
