* LaTeX Preamble                                                     :ignore:
#+TITLE: IPSP055 - Essential Industrial Design Law
#+AUTHOR: Nyameko Lisa
#+DATE: 18 May 2018
#+SUBTITLE: Assignment 03

#+LATEX_HEADER: \usepackage[margin=0.80in]{geometry}
#+LATEX_HEADER: \usepackage[url=false, backend=biber, style=ieee]{biblatex}
#+LATEX_HEADER: \usepackage{float}
#+LATEX_HEADER: \usepackage[super,negative]{nth}
#+LATEX_HEADER: \usepackage[capitalise]{cleveref}
#+LATEX_HEADER: \usepackage{pst-node,transparent,ragged2e}
#+LATEX_HEADER: \addbibresource{/home/nuk3/.spacemacs.d/org-files/bibliography.bib}
#+LATEX_HEADER: \DeclareFieldFormat[inproceedings]{citetitle}{\textit{#1}}
#+LATEX_HEADER: \DeclareFieldFormat[inproceedings]{title}{\textit{#1}}
#+LATEX_HEADER: \DeclareFieldFormat[misc]{citetitle}{#1}
#+LATEX_HEADER: \DeclareFieldFormat[misc]{title}{#1}
#+LATEX_HEADER: \renewcommand*{\bibpagespunct}{%
#+LATEX_HEADER:   \ifentrytype{inproceedings}
#+LATEX_HEADER:     {\addspace}
#+LATEX_HEADER:     {\addcomma\space}}
#+LATEX_HEADER: \AtEveryCitekey{\ifuseauthor{}{\clearname{author}}}
#+LATEX_HEADER: \AtEveryBibitem{\ifuseauthor{}{\clearname{author}}}

#+OPTIONS: toc:nil
#+LATEX_HEADER: \SpecialCoor

# Institution
#+BEGIN_EXPORT latex
\addvspace{110pt}
\centering{
\pnode(0.5\textwidth,-0.5\textheight){thisCenter}
\rput(thisCenter){%\transparent{0.25}
\includegraphics[width=2.7in]{/home/nuk3/course/llb/wipo-unisa/UNISACoatofArms.eps}}}
#+END_EXPORT

#+LaTeX: \justifying
#+LaTeX: \addvspace{110pt}
* Declaration
  :PROPERTIES:
   :UNNUMBERED: t
  :END:
  I know that plagiarism is to use someone else’s work and pass it off as my own.\\
  I know that plagiarism is wrong.\\
  I confirm that this assignment is my own work.\\
  I have acknowledged in the bibliography accompanying the assignment all the sources that I have used.\\
  I have not directly copied without acknowledgement anything from the Internet or from any other source.\\
  I have indicated every quotation and citation in a footnote or bracket linked to that quotation.\\
  I have not allowed anyone else to copy my work and to pass it off as their own work.\\
  I understand that if any unacknowledged copying whatsoever appears in my assignment I will receive zero per cent for the assignment.\\
  I am aware of the UNISA policy on plagiarism and understand that disciplinary proceedings can be instituted against me by UNISA if I contravene this policy.\\
  I indicate my understanding and acceptance of this declaration by
  entering my name here under:
    - Name: *Nyameko Lisa* (Student Number: *7874-909-3*)

** NOTE
Please note that footnotes will be denoted as [fn::This is a footnote.] and will
appear at the bottom of the page.\\
References will be denoted by cite:rsa93_designs_act and will appear at the end of the document.
\newpage

* Will the *Vision 100 Motorrad* design qualify substantially for either functional or aesthetic design protection in South Africa?
As per the definitions of [section 2(1)]cite:rsa93_tm_act and given that the
Republic is both a Paris Convention as well as a World Intellectual Property
Organisation (WIPO) Member State, [article 15(1)]cite:wto17_trips, [article
1(2)]cite:wipo83_paris_conve_protect_ip, cite:wipo25_hague_agreement, South African statutory design
legislation is in compliance with International Conventions and legal instruments.\\

As per the provisions of cite:rsa78_patents_act, patent rights seek to protect
the principle underlying an inventive process or product. In contrast the South
African Designs Act No. 195 of 1993 cite:rsa93_designs_act, provides provisions
for the protection of only the physical form of articles of manufacture intended
to be multiplied by industrial processes, [section 14(4)]cite:rsa93_designs_act.

** Requirements for design protection

Judson Beaumont, who will henceforth be referred to as the *``proprietor''* of
the Beaver Cabinet design which will in turn be referred to as the *``article''*, as
per the provisions of [section 1(1)]cite:rsa93_designs_act and his Straight Line
Designs studio should be advised that the legislation makes provision for both
_aesthetic designs_ (Part A) as well as _functional designs_ (Part F)
registrations, as per the provisions of [section
14(1)(a-b)]cite:rsa93_designs_act.

*** Aesthetic designs

As per the provisions of [section 1(1)]cite:rsa93_designs_act, which stipulates
that @@latex:\textit{``...any design applied to any article, whether for the
pattern or the shape or the configuration or the ornamentation thereof, or for
any two or more of these purposes, and by whatever means is applied, having
features which appeal to and are judged solely by the eye, irrespective of the
aesthetic quality thereof...''}@@, as was stipulated by Judge Corbett in
citetitle:corbett84_homecraft_steel_v_sm_hare:
#+BEGIN_QUOTE
@@latex:\textit{To qualify as a design, an article must have some special feature
which appeals to the eye and distinguishes it from others of its class.''}@@
#+END_QUOTE
The *proprietor* would be advised to pursue aesthetic design registration for
their *article*.

*** Functional designs
Again as per the provisions of [section 1(1)]cite:rsa93_designs_act, the
definition of a function design is @@latex:\textit{``...any design applied to any article,
either for the pattern or the shape or the configuration thereof, or for any two
or more of these purposes, and by whatever means it is applied, having features
which are necessitated by the function which the article to which the design is
applied, is to perform, and includes an integrated circuit topography, a mask
work and a series of mask works...''}@@.\\

Whist it is possible for the *proprietor* to lodge both functional and aesthetic
design registration applications in respect of their *article*, as per the
provisions of [section 14(1)(b)(ii)]cite:rsa93_designs_act, it is not obviously
apparent that there are any functional features of the Beaver Cabinet article
that require protection of purely functional design features or methods and
principles of it's construction [section 14(4)]cite:rsa93_designs_act, /``that
are not commonplace in the art in question''/. Without any evidence to the
contrary, Straight Line Designs would most likely be unsuccessful in seeking
functional design registration for their *article*.

*** Originality

As per the provisions of [section 14(1)(a)]cite:rsa93_designs_act, should Judson
be able to demonstrate that his Beaver Cabinet is both *new* and *original*, he
may in the prescribed manner and on payment of the prescribed fee, apply for
aesthetic design registration. Moreover the Beaver Cabinet must be different
from or not form part of the *state of the art* within a grace period of six
months from the date of first disclosure, or release date [section
14(2)(b)]cite:rsa93_designs_act. Where state of the art comprises of all matter
which has been made available to the public, within or outside the Republic, by
written means, usage or any other form [section 14(3)(a)]cite:rsa93_designs_act,
including all matter contained in pending registration applications [section
14(3)(b)]cite:rsa93_designs_act. Courts of the Republic have interpreted the
meaning of /`original'/ to coincide with that definition outlined in
cite:rsa78_copyrightact, and which was further elaborated on by Judge Van
Heerden in citetitle:vheerden71_xactics_v_tailored_containers, where he
explained that:
#+BEGIN_QUOTE
@@latex:\textit{``I have accordingly come to the conclusion that applicant's registered design
68/346 was not new or original by reason of the fact that a design not substantially
different therefrom had already been described in a printed publication before the
date of application for registration.''}@@
#+END_QUOTE

Moreover in respect of the prior art depicted in *Figure 2*, it could be argued
that the commonplace in the art elements and aspects demonstrated therein,
describe features that are necessarily determined by the function of the article
in question and are *not* registrable as designs in and of themselves.

In terms of the definition of  F  "design" in s 1 (1) of the Act, any feature which is dictated solely by the function which the article is intended to perform, is excluded from protection under the Act. The top and bottom flanges and the return lip on the bottom flange are purely functional in that they provide the requisite rigidity and facilitate handling of the fascias. The fluting on the face  G  of the design serves the functional purpose of providing additional rigidity. In regard to the question of when functional features are excluded from protection, see Amp Incorporated v Unilux (Pty) Ltd [1972] RPC 103; Swisstool Manufacturing Co v Omega Africa Plastics (supra ). See also the commentary on "method or principle of construction" in Russel-Clarke (supra at 27 - 28) and Kestos Ltd v Kempat Ltd &  H  Kemp [1936] 53 RPC 139 at 151.

Irrespective of the fact that the Vission 100 incorporates registrable as well
as unregistrable features, it is the registratble features that the BMW would be
encouraged to persue.
* Are there any other forms of intellectual property protection available to BMW for the Vision 100 Motorrad?

* State whether the actions of Carsmart International amount to infringement of the South African design for the Vision 100 Motorrad lights, to which Carsmart counterclaims.

* Is it possible to register a design right for the semiconductor chip that regulates the control of the `Flexframe' of the Vision 100 Motorrad?

* Analyse the possibility of design infringement. [20]

As per the definitions of [section 2(1)]cite:rsa93_tm_act and given that the
Republic is both a Paris Convention as well as a World Intellectual Property
Organisation (WIPO) Member State, [article 15(1)]cite:wto17_trips, [article
1(2)]cite:wipo83_paris_conve_protect_ip, cite:wipo25_hague_agreement, South African statutory design
legislation is in compliance with International Conventions and legal instruments.\\

As per the provisions of cite:rsa78_patents_act, patent rights seek to protect
the principle underlying an inventive process or product. In contrast the South
African Designs Act No. 195 of 1993 cite:rsa93_designs_act, provides provisions
for the protection of only the physical form of articles of manufacture intended
to be multiplied by industrial processes, [section
14(4)]cite:rsa93_designs_act.\\

As per the provisions of [section 20(1)]cite:rsa93_designs_act, the effect of
registration of the design in *Figure 2* shall grant the registered proprietor
in the Republic, for the [section 22(1)]cite:rsa93_designs_act, duration of
registration the exclusive right to exclude others from *making* or *using* any
article included in the class in which their design is registered and embodying
the registered design or a design not substantially different from the
registered design.

** Infringement

As per the provisions of [section 35(1)]cite:rsa93_designs_act, the registered
proprietor of the design in *Figure 2* may institute proceedings for
infringement against Deniz Karasahin, adesignaward.com, for the *unauthorised
manufacture* of their Osteoid design, which bears resemblance not substantially
different to the registered design as an article of the same class.

** Visual Judgement of Similarity

As per citetitle:corbett84_homecraft_steel_v_sm_hare
cite:corbett84_homecraft_steel_v_sm_hare, the test for infringement is a purely
visual judgement according to the observation of the likely customer where Judge
Corbett  referred to Judge Eloff in preceding case law,
#+BEGIN_QUOTE
@@latex:\textit{``to hold that while the eye is to be the eye of the Court, the
Court should view the design through the spectacles of the customer''}@@
#+END_QUOTE
wherein the designs are viewed and considered both independently as well as
side by side,
#+BEGIN_QUOTE
@@latex:\textit{``an article must have some special feature which appeals to the
eye and distinguishes it from other of its class... This must be decided by the
eye; and in applying this visual test the Court must bear in mind the reaction
of the likely customer. The two designs must be viewed and compared side by side
and also separately.''}@@
#+END_QUOTE

** Novelty and Originality

When analysing the possibility of infringement, the state of the art and the
degree of novelty and originality achieved by the registered design is also an
important factor, in reference to preceding case law, Judge Corbett stipulates,
cite:corbett84_homecraft_steel_v_sm_hare that,
#+BEGIN_QUOTE
@@latex:\textit{``If only small differences seperate the registered design from
what has gone before, then eqaully small differences between the alleged
infringement and the regsitered design will be held to be sufficient to avoid
infringement...''}@@
#+END_QUOTE
There are however significant differences between the two designs, in *shape* and / or
*configuration*, and there is no risk of a member of the public or likely customer
confusing the two designs, where in substantiating proceedings for design
infringement applicants have in the past relied on alleged infringement of their
registered designs as well as on the delict of passing off,
citetitle:corbett84_homecraft_steel_v_sm_hare cite:corbett84_homecraft_steel_v_sm_hare,
citetitle:vdwesthuizen02_slavepak_v_buddy cite:vdwesthuizen02_slavepak_v_buddy,
citetitle:duplessis02_koninklijke_phillips_v_kenwood
cite:duplessis02_koninklijke_phillips_v_kenwood.\\

As per the provisions of [section 35(3)]cite:rsa93_designs_act, the plaintiff
would likely seek and interdict [subsection (a)], assuming the prototype is still in the
developmental stages and has not as yet gone into production, and would not
likely pursue surrender of goods or damages [subsections (b)-(-d)]. Based on the
above arguments however, the plaintiff is not likely to succeed with any design
infringement actions within the Republic.

** Recommendation for design and patent protection

The designer Deniz Karasahin, would be strongly recommended to not only seek
aesthetic and functional design protection, but also patent protection for their
Osteiod design. As per the definitions specified in [section
2]cite:rsa78_patents_act and [Article 27(1)]cite:wto17_trips, the Osteoid prototype
need satisfy the provisions for a patent to be granted under [section
25]cite:rsa78_patents_act, wherein subsection (1) of that section of the Act
stipulates that a patent may be granted for a *new* invention[fn:1], involving
an *inventive step*[fn:2] and has application to trade or
industry[fn::Contributing to the medical healing process.].

*** Aesthetic design registration
As per the provisions of [section 1(1)]cite:rsa93_designs_act, which stipulates
that @@latex:\textit{``...any design applied to any article, whether for the
pattern or the shape or the configuration or the ornamentation thereof, or for
any two or more of these purposes, and by whatever means is applied, having
features which appeal to and are judged solely by the eye, irrespective of the
aesthetic quality thereof...''}@@, as was stipulated by Judge Corbett in
citetitle:corbett84_homecraft_steel_v_sm_hare:
#+BEGIN_QUOTE
@@latex:\textit{To qualify as a design, an article must have some special feature
which appeals to the eye and distinguishes it from others of its class.''}@@
#+END_QUOTE
The *proprietor* of the Osteoid would be advised to pursue aesthetic design
registration for their *article*.

*** Functional design registration
Again as per the provisions of [section 1(1)]cite:rsa93_designs_act, the
definition of a function design is @@latex:\textit{``...any design applied to
any article, either for the pattern or the shape or the configuration thereof,
or for any two or more of these purposes, and by whatever means it is applied,
having features which are necessitated by the function which the article to
which the design is applied, is to perform, and includes an integrated circuit
topography, a mask work and a series of mask works...''}@@.\\

The *proprietor*, Deniz Karasahin, is strongly recommended to lodge both
functional and aesthetic design registration applications in respect of their
*article*, as per the provisions of [section
14(1)(b)(ii)]cite:rsa93_designs_act, and the methods and principles of it's
construction[fn:1] [section 14(4)]cite:rsa93_designs_act, /``that are not
commonplace in the art in question''/ and the functional features of the
3D-printed medical cast that requires protection of purely functional design
features[fn:2].

* Bibliography                                                       :ignore:
\printbibliography

#  LocalWords:  patentable Osteoid

* Footnotes

[fn:1] Novel 3D-printed design.

[fn:2] Innovative low-intensity pulsed ultrasound system.
