* LaTeX Preamble                                                     :ignore:
#+TITLE: IPSP089 - Legal Aspects of Traditional Knowledge and Biodiversity
#+AUTHOR: Nyameko Lisa
#+DATE: 30 September 2018
#+SUBTITLE: Assignment 2: 656029

#+LATEX_HEADER: \usepackage[margin=0.80in]{geometry}
#+LATEX_HEADER: \usepackage[backend=biber, style=ieee, url=false]{biblatex}
#+LATEX_HEADER: \usepackage{float}
#+LATEX_HEADER: \usepackage[super,negative]{nth}
#+LATEX_HEADER: \usepackage[capitalise]{cleveref}
#+LATEX_HEADER: \usepackage{pst-node,transparent,ragged2e}
#+LATEX_HEADER: \addbibresource{/home/nlisa/.spacemacs.d/org-files/bibliography.bib}
#+LATEX_HEADER: \DeclareFieldFormat[inproceedings]{citetitle}{\textit{#1}}
#+LATEX_HEADER: \DeclareFieldFormat[inproceedings]{title}{\textit{#1}}
#+LATEX_HEADER: \DeclareFieldFormat[misc]{citetitle}{#1}
#+LATEX_HEADER: \DeclareFieldFormat[misc]{title}{#1}
#+LATEX_HEADER: \renewcommand*{\bibpagespunct}{%
#+LATEX_HEADER:   \ifentrytype{inproceedings}
#+LATEX_HEADER:     {\addspace}
#+LATEX_HEADER:     {\addcomma\space}}
#+LATEX_HEADER: \AtEveryCitekey{\ifuseauthor{}{\clearname{author}}}
#+LATEX_HEADER: \AtEveryBibitem{\ifuseauthor{}{\clearname{author}}}

#+OPTIONS: toc:nil
#+LATEX_HEADER: \SpecialCoor

# Institution
#+BEGIN_EXPORT latex
\addvspace{110pt}
\centering{
\pnode(0.5\textwidth,-0.5\textheight){thisCenter}
\rput(thisCenter){%\transparent{0.25}
\includegraphics[width=2.7in]{/home/nuk3/course/llb/wipo-unisa/UNISACoatofArms.eps}}}
#+END_EXPORT

#+LaTeX: \justifying
#+LaTeX: \addvspace{110pt}
* Declaration
  :PROPERTIES:
   :UNNUMBERED: t
  :END:
  I know that plagiarism is to use someone else’s work and pass it off as my own.\\
  I know that plagiarism is wrong.\\
  I confirm that this assignment is my own work.\\
  I have acknowledged in the bibliography accompanying the assignment all the sources that I have used.\\
  I have not directly copied without acknowledgement anything from the Internet or from any other source.\\
  I have indicated every quotation and citation in a footnote or bracket linked to that quotation.\\
  I have not allowed anyone else to copy my work and to pass it off as their own work.\\
  I understand that if any unacknowledged copying whatsoever appears in my assignment I will receive zero per cent for the assignment.\\
  I am aware of the UNISA policy on plagiarism and understand that disciplinary proceedings can be instituted against me by UNISA if I contravene this policy.\\
  I indicate my understanding and acceptance of this declaration by
  entering my name here under:
    - Name: *Nyameko Lisa* (Student Number: *7874-909-3*)

** NOTE
Please note that footnotes will be denoted as [fn::This is a footnote.] and will
appear at the bottom of the page.\\
References will be denoted by cite:rsa93_tm_act and will appear at the end of the document.
\newpage

* Question 1 [50]
Discuss the following in respect of traditional cultural expressions
(expressions of folklore):

** Why is there a need to protect expressions of folklore? (20)

Folklore is an important element of a nation's cultural heritage, providing its
people with an avenue for self-expression and it exists as a means of a
country's social identity. Traditional expressions have generally been
characterized as a broad set of oral and or written literary, artistic,
religious, scientific, technological works and other traditions and productions
that are transmitted from one generation to another, and whose creators need not
necessarily be indigenous peoples.\\

With regards to folklore, aspects related to its subject matter, technological
and methodological content need to be taken into consideration. Thus it is
important to consider not only protection from a copyright perspective, but also
the mechanisms of industrial property protection, including patents, trademarks
and industrial designs.\\

The need for protection of expressions of folklore arises where the creators or
rights holders, would need to prevent others from reproducing their creations or
disseminating them to the public through performance or broadcast, /(i.e. law of
copyright)/; and to restrict the unauthorized misappropriation of technological
and methodological ideas, inventions, crafts, designs and carvings, /(i.e. laws
of patents, trademarks and industrial designs)/. Moreover, informal traditional
customary regimes may not provide adequate protection against cultural, economic
or commercial exploitation.\\

Both globalization and the advent of technological telecommunications advances
in recent history, have lead to the improper exploitation of cultural
expressions of folklore currently experienced today. The misappropriation of the
intellectual property rights that /`should'/ be enjoyed by a people, resulting
from their endeavors and accumulated cultural heritage can take a number of
forms, from commercial exploitation to adaptation and distortion of the original
works.\\

There exists a clear need for the development of both national and international
instruments \ frameworks, providing legal protection against the exploitation of
cultural expressions of folklore, without any compensation to their originating
communities. Moreover, litigation processes are also required to reclassify
those expressions of folklore that were previously considered to belong to the
public domain. Not forgetting the subsequent infringement and sanctioning
procedures with regards to infringement of the rights in `works of folklore'.

** The WIPO / UNESCO's Model Provisions on the issue. (30)

cite:wipo86_berne

cite:wto17_trips

As per the provisions of [article 15(4)(a-b)]cite:wipo86_berne, although not
explicitly limited to, nor directly referring to folklore, member Union
countries may use their respective national legislation to designate a competent
authority to represent, protect and enforce the rights of an unknown, but
assumed to be a domiciled in said country, author of an unpublished work.




* Bibliography                                                       :ignore:
\printbibliography
