* LaTeX Preamble                                                     :ignore:
#+TITLE: IPSP089 - Legal Aspects of Traditional Knowledge and Bioduversity
#+AUTHOR: Nyameko Lisa
#+DATE: 31 August 2018
#+SUBTITLE: Assignment 1: 781450

#+LATEX_HEADER: \usepackage[margin=0.80in]{geometry}
#+LATEX_HEADER: \usepackage[backend=biber, style=ieee, url=false]{biblatex}
#+LATEX_HEADER: \usepackage{float}
#+LATEX_HEADER: \usepackage[super,negative]{nth}
#+LATEX_HEADER: \usepackage[capitalise]{cleveref}
#+LATEX_HEADER: \usepackage{pst-node,transparent,ragged2e}
#+LATEX_HEADER: \addbibresource{/home/nuk3/.spacemacs.d/org-files/bibliography.bib}
#+LATEX_HEADER: \DeclareFieldFormat[inproceedings]{citetitle}{\textit{#1}}
#+LATEX_HEADER: \DeclareFieldFormat[inproceedings]{title}{\textit{#1}}
#+LATEX_HEADER: \DeclareFieldFormat[misc]{citetitle}{#1}
#+LATEX_HEADER: \DeclareFieldFormat[misc]{title}{#1}
#+LATEX_HEADER: \renewcommand*{\bibpagespunct}{%
#+LATEX_HEADER:   \ifentrytype{inproceedings}
#+LATEX_HEADER:     {\addspace}
#+LATEX_HEADER:     {\addcomma\space}}
#+LATEX_HEADER: \AtEveryCitekey{\ifuseauthor{}{\clearname{author}}}
#+LATEX_HEADER: \AtEveryBibitem{\ifuseauthor{}{\clearname{author}}}

#+OPTIONS: toc:nil
#+LATEX_HEADER: \SpecialCoor

# Institution
#+BEGIN_EXPORT latex
\addvspace{110pt}
\centering{
\pnode(0.5\textwidth,-0.5\textheight){thisCenter}
\rput(thisCenter){%\transparent{0.25}
\includegraphics[width=2.7in]{/home/nuk3/course/llb/wipo-unisa/UNISACoatofArms.eps}}}
#+END_EXPORT

#+LaTeX: \justifying
#+LaTeX: \addvspace{110pt}
* Declaration
  :PROPERTIES:
   :UNNUMBERED: t
  :END:
  I know that plagiarism is to use someone else’s work and pass it off as my own.\\
  I know that plagiarism is wrong.\\
  I confirm that this assignment is my own work.\\
  I have acknowledged in the bibliography accompanying the assignment all the sources that I have used.\\
  I have not directly copied without acknowledgement anything from the Internet or from any other source.\\
  I have indicated every quotation and citation in a footnote or bracket linked to that quotation.\\
  I have not allowed anyone else to copy my work and to pass it off as their own work.\\
  I understand that if any unacknowledged copying whatsoever appears in my assignment I will receive zero per cent for the assignment.\\
  I am aware of the UNISA policy on plagiarism and understand that disciplinary proceedings can be instituted against me by UNISA if I contravene this policy.\\
  I indicate my understanding and acceptance of this declaration by
  entering my name here under:
    - Name: *Nyameko Lisa* (Student Number: *7874-909-3*)

** NOTE
Please note that footnotes will be denoted as [fn::This is a footnote.] and will
appear at the bottom of the page.\\
References will be denoted by cite:rsa93_tm_act and will appear at the end of the document.
\newpage

* Question 1 [50]

cite:simelane09_african_trad_knowl_sys_biodiv_manag,saurombe09_protection_indigenous_trad_knowl_through_ip,masango14_trad_knowl_cultural_express_protect,masango10_indigenous_trad_knowl_protect_prospects,amechi15_trad_knowl_medical_uses_plants_pat_sa,amechi15_leverag_trad_knowl_medicinal,geyer10_towards_clearer_defin_underst_indi,rsa78_patents_act,wto17_trips
** Compare and contrast the terms ``traditional knowledge'' and ``indigenous knowledge''. In your answer state whether the /maca/ plant falls within these definitions. (10)
Traditional knowledge systems, creations, innovations, or cultural expressions
refer to /literary, artistic or scientific works, performances, scientific
inventions or discoveries, designs, marks or symbols/, that have evolved in
response to a changing environment and are inherited from one generation to
another within a particular group of people or their territory.\\

Although there exists no universally accepted formal definition for indigenous
peoples, `indigenous knowledge' is synonymous with and in fact a subset to,
`traditional knowledge' in terms of its scope, transmission and diversity.
Whilst their distinction is indeed subtle, `traditional knowledge' held by
indigenous people, denotes `indigenous knowledge'.\\

For example, knowledge disseminated through traditional means amongst the
Khoisan peoples of Southern Africa, constitutes `indigenous' or `traditional
knowledge'. In contrast however, the information passed down through traditional
means, by colonial Dutch settlers in the Cape can be described as `traditional
knowledge', but *not* 'indigenous knowledge'.\\

Given that the maca has long been valued for its ability to enhance fertility in
humans and livestock, it does indeed constitute `traditional knowledge'.
Moreover, given that indigenous peoples have used it the same way for
generations, as a potato-like food source, as well as a supplement for
livestock, appreciated not only for its rich protein and vitamin content, but
for it's sexual performance and fertility enhancement, such use also constitutes
`indigenous knowledge'.

** How has knowledge been protected customarily? (10)

Informal regimes relied on mechanisms based on non-systematic and undocumented
rules, obligations and rights, that are enforced either by elders or religious
leaders. These regimes are `self-legitimised' within and across the community
though the accrual of consensus to abide by and adhere to these laws and
rules.\\

Generally speaking customary law is not recognised by legal institutions outside
of the relevant communities where they were originally established. The culture
and history of a people are preserved by the community elders and leaders, who
are also responsible for determining eligibility and allocation of various arts
to be practised amongst the community's artisans, as well as dispute resolution.

** What are the problems confronting rights holders (in our case the people in Junin Peru)? (10)

Many existing legal frameworks are inadequate at resolving or determining a
common denominator between the economic interests of commercialisation, and the
traditional interests of the people of Junin, Peru. Generally speaking, the lack
of representation in litigation, coupled with inadequate protection has
resulted in the dismissal and disrespect of the indigenous people of Peru, who
/arguably should/ have enjoyed the conferral of intellectual property rights in
relation to the `indigenous knowledge' regarding the uses of the maca, and again
/arguably should/ have control over its exploitation by others.\\

Globalisation has given rise to a reluctance of younger generations to learn the
traditional and cultural practices. Coupled with the absence of willing heirs
and participants, means that there is significant risk of loss of the
traditional and indigenous knowledge regarding the maca, should it be
inadequately documented and ill-preserved.\\

Generally speaking modern society holds a prejudiced view, denigrating
traditional knowledge as `primitive'. This lack of appreciation for such
knowledge, stems from the indigenous people traditionally exploiting the effects
of the maca plant, without describing them in terms of the molecular and chemical
reactions of modern biochemical interactions. This has seen two United States
patents granted for the chemical components, specifically the methods of
extraction form the active ingredients of the maca plant, and not the plant
itself.

** What is WIPO's role in protecting traditional knowledge? (20)
cite:wto17_trips,wipo83_paris_conve_protect_ip
The WIPO General Assembly established an Intergovernmental Committee on
Intellectual Property and Genetic Resources, Traditional Knowledge and Folklore
focusing primarily on three issues of discussion:
- access to genetic resources and benefit-sharing,
- the protection of traditional knowledge, innovations and creativity, and
- the protection of expressions of folklore, including handicrafts.

Where the scope of the current work programme of WIPO includes:
- development of resources detailing methods to implement existing mechanisms of
  intellectual property frameworks for the protection of transitional knowledge,
- complimentary to the above, hands-on national training workshop on existing
  intellectual property systems and their use in the protection of traditional
  knowledge,
- with respect to documentation and preservation of transitional knowledge,
  establishing mechanisms of their standardisation and recognition as
  instruments of intellectual property,
- fact finding missions, to providing evidence of practical implementations for
  the protection of traditional knowledge under existing intellectual property
  mechanisms,
- fact finding missions and feasibility studies into the applicability of
  customary laws to traditional knowledge and their integration with existing
  statutory regulations,
- pilot project on the collective acquisition, management, enforcement of
  intellectual property rights within traditional knowledge.

* Bibliography                                                       :ignore:
\printbibliography
