* LaTeX Preamble                                                     :ignore:
#+TITLE: IPSP089 - Legal Aspects of Traditional Knowledge and Biodiversity
#+AUTHOR: Nyameko Lisa
#+DATE: 19 October 2018
#+SUBTITLE: Portfolio Exam: 743336

#+LATEX_HEADER: \usepackage[margin=0.80in]{geometry}
#+LATEX_HEADER: \usepackage[backend=biber, style=ieee, url=false]{biblatex}
#+LATEX_HEADER: \usepackage{float}
#+LATEX_HEADER: \usepackage[super,negative]{nth}
#+LATEX_HEADER: \usepackage[capitalise]{cleveref}
#+LATEX_HEADER: \usepackage{pst-node,transparent,ragged2e}
#+LATEX_HEADER: \addbibresource{/home/nlisa/.spacemacs.d/org-files/bibliography.bib}
#+LATEX_HEADER: \DeclareFieldFormat[inproceedings]{citetitle}{\textit{#1}}
#+LATEX_HEADER: \DeclareFieldFormat[inproceedings]{title}{\textit{#1}}
#+LATEX_HEADER: \DeclareFieldFormat[misc]{citetitle}{#1}
#+LATEX_HEADER: \DeclareFieldFormat[misc]{title}{#1}
#+LATEX_HEADER: \renewcommand*{\bibpagespunct}{%
#+LATEX_HEADER:   \ifentrytype{inproceedings}
#+LATEX_HEADER:     {\addspace}
#+LATEX_HEADER:     {\addcomma\space}}
#+LATEX_HEADER: \AtEveryCitekey{\ifuseauthor{}{\clearname{author}}}
#+LATEX_HEADER: \AtEveryBibitem{\ifuseauthor{}{\clearname{author}}}

#+OPTIONS: toc:nil
#+LATEX_HEADER: \SpecialCoor

# Institution
#+BEGIN_EXPORT latex
\addvspace{110pt}
\centering{
\pnode(0.5\textwidth,-0.5\textheight){thisCenter}
\rput(thisCenter){%\transparent{0.25}
\includegraphics[width=2.7in]{/home/nlisa/course/llb/wipo-unisa/UNISACoatofArms.eps}}}
#+END_EXPORT

#+LaTeX: \justifying
#+LaTeX: \addvspace{110pt}
* Declaration
  :PROPERTIES:
   :UNNUMBERED: t
  :END:
  I know that plagiarism is to use someone else’s work and pass it off as my own.\\
  I know that plagiarism is wrong.\\
  I confirm that this assignment is my own work.\\
  I have acknowledged in the bibliography accompanying the assignment all the sources that I have used.\\
  I have not directly copied without acknowledgement anything from the Internet or from any other source.\\
  I have indicated every quotation and citation in a footnote or bracket linked to that quotation.\\
  I have not allowed anyone else to copy my work and to pass it off as their own work.\\
  I understand that if any unacknowledged copying whatsoever appears in my assignment I will receive zero per cent for the assignment.\\
  I am aware of the UNISA policy on plagiarism and understand that disciplinary proceedings can be instituted against me by UNISA if I contravene this policy.\\
  I indicate my understanding and acceptance of this declaration by
  entering my name here under:
    - Name: *Nyameko Lisa* (Student Number: *7874-909-3*)

** NOTE
Please note that footnotes will be denoted as [fn::This is a footnote.] and will
appear at the bottom of the page.\\
References will be denoted by cite:rsa93_tm_act and will appear at the end of the document.
\newpage

* Question 1 [25]

Critically analyse this statement:

The concept `traditional knowledge' has many facets and encompasses several
components. What characterizes traditional knowledge is the fact that,
generally, it is not produced systematically, but in accordance with the
individual creator's, or the collective creators' responses to their cultural
environment and their interaction with it.

* Question 2 [25]

Discuss how traditional crafts are protected. In your answer, refer to relevant
case studies, also the use of alternative forms of intellectual property in
dealing with this issue.

* Question 3 [25]

/Read the following statement and answer the question that follows:/

In developed countries, expressions of folklore are generally considered as
belonging to the public domain. This approach explains why, in the main,
developed countries generally did not establish a legal protection of the
manifold national or other communicate interests related to the utilization of
expressions of folklore.

** Do you agree with the statement? Indicate and explain your reasons. (15)

** Give an indication of what is the position in developing countries. (10)

* Question 4 [25]

Identify the issues relating to the protection of ethnobotanical knowledge. In your answer refer to the following:

** Protection against exploitation of industrial property. (10)

** Protection for exploitation of industrial property. (15)

* Bibliography                                                       :ignore:
\printbibliography
