#+TITLE: IPSP01X - Essential Copyright Law
#+SUBTITLE: Assignment 1 - Unique Number: 659072
* LaTeX Preamble                                                     :ignore:
#+LATEX_HEADER: \usepackage[backend=bibtex, style=ieee]{biblatex}
#+LATEX_HEADER: \addbibresource{~/course/training/csir/novellasers/bibliography/bibliography.bib}
#+LATEX_HEADER: \DeclareFieldFormat[inproceedings]{citetitle}{\textit{#1}}
#+LATEX_HEADER: \DeclareFieldFormat[inproceedings]{title}{\textit{#1}}
#+LATEX_HEADER: \DeclareFieldFormat[inproceedings]{number}{#1}
#+LATEX_HEADER: \renewcommand*{\bibpagespunct}{%
#+LATEX_HEADER:   \ifentrytype{inproceedings}
#+LATEX_HEADER:     {\addspace}
#+LATEX_HEADER:     {\addcomma\space}}
#+LATEX_HEADER: \AtEveryCitekey{\ifuseauthor{}{\clearname{author}}}
#+LATEX_HEADER: \AtEveryBibitem{\ifuseauthor{}{\clearname{author}}}
* Declaration
  :PROPERTIES:
   :UNNUMBERED: t
  :END:
  - I know that plagiarism is to use someone else’s work and pass it off as my own.
  - I know that plagiarism is wrong.
  - I confirm that this assignment is my own work.
  - I have acknowledged in the bibliography accompanying the assignment all the sources that I have used.
  - I have not directly copied without acknowledgement anything from the Internet or from any other source.
  - I have indicated every quotation and citation in a footnote or bracket linked to that quotation.
  - I have not allowed anyone else to copy my work and to pass it off as their own work.
  - I understand that if any unacknowledged copying whatsoever appears in my assignment I will receive zero per cent for the assignment.
  - I am aware of the UNISA policy on plagiarism and understand that disciplinary proceedings can be instituted against me by UNISA if I contravene this policy.
  - I indicate my understanding and acceptance of this declaration by
    entering my name hereunder:
    - Name: *Nyameko Lisa*
    - Email: *Lisa.Nyameko@gmail.com*
    - Student Number: *7874-909-3*
* Authors of English Study Guide
cite:corbett95_waylite_v_fnb citetitle:corbett95_waylite_v_fnb

cite:mccreath91_juta_v_dekoker

cite:burger85_bosal_afrika_v_grapnel
* Cite Act
cite:rsa78_copyrightact
* Bibliography                                                       :ignore:
#+BEGIN_EXPORT latex
\printbibliography
#+END_EXPORT
