
* LaTeX Preamble                                                     :ignore:
#+TITLE: IPSP066 - Internet Aspects of Copyright and Trade Marks
#+AUTHOR: Nyameko Lisa
#+DATE: 26 April 2018
#+SUBTITLE: Assignment 02 - 827787

#+LATEX_HEADER: \usepackage[margin=0.80in]{geometry}
#+LATEX_HEADER: \usepackage[backend=biber, style=ieee, url=false]{biblatex}
#+LATEX_HEADER: \usepackage{float}
#+LATEX_HEADER: \usepackage[super,negative]{nth}
#+LATEX_HEADER: \usepackage[capitalise]{cleveref}
#+LATEX_HEADER: \usepackage{pst-node,transparent,ragged2e}
#+LATEX_HEADER: \addbibresource{/home/nuk3/.spacemacs.d/org-files/bibliography.bib}
#+LATEX_HEADER: \DeclareFieldFormat[inproceedings]{citetitle}{\textit{#1}}
#+LATEX_HEADER: \DeclareFieldFormat[inproceedings]{title}{\textit{#1}}
#+LATEX_HEADER: \DeclareFieldFormat[misc]{citetitle}{#1}
#+LATEX_HEADER: \DeclareFieldFormat[misc]{title}{#1}
#+LATEX_HEADER: \renewcommand*{\bibpagespunct}{%
#+LATEX_HEADER:   \ifentrytype{inproceedings}
#+LATEX_HEADER:     {\addspace}
#+LATEX_HEADER:     {\addcomma\space}}
#+LATEX_HEADER: \AtEveryCitekey{\ifuseauthor{}{\clearname{author}}}
#+LATEX_HEADER: \AtEveryBibitem{\ifuseauthor{}{\clearname{author}}}

#+OPTIONS: toc:nil
#+LATEX_HEADER: \SpecialCoor

# Institution
#+BEGIN_EXPORT latex
\addvspace{110pt}
\centering{
\pnode(0.5\textwidth,-0.5\textheight){thisCenter}
\rput(thisCenter){%\transparent{0.25}
\includegraphics[width=2.7in]{/home/nuk3/course/llb/wipo-unisa/UNISACoatofArms.eps}}}
#+END_EXPORT

#+LaTeX: \justifying
#+LaTeX: \addvspace{110pt}
* Declaration
  :PROPERTIES:
   :UNNUMBERED: t
  :END:
  I know that plagiarism is to use someone else’s work and pass it off as my own.\\
  I know that plagiarism is wrong.\\
  I confirm that this assignment is my own work.\\
  I have acknowledged in the bibliography accompanying the assignment all the sources that I have used.\\
  I have not directly copied without acknowledgement anything from the Internet or from any other source.\\
  I have indicated every quotation and citation in a footnote or bracket linked to that quotation.\\
  I have not allowed anyone else to copy my work and to pass it off as their own work.\\
  I understand that if any unacknowledged copying whatsoever appears in my assignment I will receive zero per cent for the assignment.\\
  I am aware of the UNISA policy on plagiarism and understand that disciplinary proceedings can be instituted against me by UNISA if I contravene this policy.\\
  I indicate my understanding and acceptance of this declaration by
  entering my name here under:
    - Name: *Nyameko Lisa* (Student Number: *7874-909-3*)

** NOTE
Please note that footnotes will be denoted as [fn::This is a footnote.] and will
appear at the bottom of the page.\\
References will be denoted by cite:rsa78_copyrightact and will appear at the end of the document.
\newpage

* Will Sibusiso be liable if consent from the rights holders has not been obtained? To whom will he be liable?

As a Convention Member the provisions of [section 5]cite:rsa78_copyrightact,
[section 104(c,d)]cite:usa76_title17_us_copyright_act, [Article
9(1)]cite:wto17_trips, [Article 1(2)]cite:eurlex00_elec_commerce, [Article
5(2)]cite:wipo86_berne and [Article 1(4)]cite:wipo96_copyright_treaty which
dictate that the statues of the Republic shall govern international copyright
protection as it pertains to the Internet. Furthermore as per the provisions of
[sections 1 and 2(1)(b,e)]cite:rsa78_copyrightact, [sections 101 and
102(a)(2,7)]cite:usa76_title17_us_copyright_act and [Article
2(1)]cite:wipo86_berne the sound recordings shall be considered as *protected
artistic works* or *sound recordings*, where the samples of those works
constitute *adaptations* or *derivative works*.\\

As per the provisions of [sections 1, 3, 4(1)(a)]cite:rsa78_copyrightact,
[section 101]cite:usa76_title17_us_copyright_act, [Article 14]cite:wto17_trips,
[Articles 2 and 3]cite:wipo96_wppt, [Article 3 and 9(1)]cite:wipo86_berne, the
*authors*, will in this instance be considered as the rights holders of the
sound recording samples, and they are understood to be the performers,
producers, licensees and broadcasting organisations of the sound recordings.\\

Linking is a means of exploiting third-party content on the Internet, and thus
enhancing a web-page with coloured or underlined descriptive words *Hyperlinked*
to Uniform Resource Locator (URL), linking to the audio samples. The mere
creation of the links does not in and of themselves constitute copyright
infringement.\\

However, depending on the licensing / contractual conditions of the links to the
samples, Sibusiso may find himself liable to the proprietors and content
generators of the sites hosted on servers in the United States of America on
which the samples appear, *in addition to* the original authors of the sound
recordings for contributory infringement, should the sound recordings be hosted
on those American servers illegally.

* Where will an infringement action against him be instituted?
Infringement action can be instituted against either within the Republic or within the United States of America.

* What law will apply?
The following are potential statutory rights of the respective holders that may be affected:

- Exclusive right of reproduction [section 9(a)]cite:rsa78_copyrightact,
  [section 106(1)]cite:usa76_title17_us_copyright_act, [Article 9(1) and
  (2)]cite:wipo86_berne, [Article 7 and 11]cite:wipo96_wppt and [Article
  2(a-e)]cite:eurlex01_harmonisation,

- Exclusive right of offering by way of trade, directly or indirectly, a
  reproduction of the sound recording [section 9(b)]cite:rsa78_copyrightact, [section 106(3)]cite:usa76_title17_us_copyright_act,

- Exclusive right of publication, distribution or broadcast to the public, or
  causing the sound recording to be transmitted in a diffusion service [section
  9(c-d)]cite:rsa78_copyrightact, [Article
  11@@latex:\textsuperscript{bis}@@(1)(i)-(ii)]cite:wipo86_berne, [Article
  6(1)]cite:wipo96_copyright_treaty, [Article 8(1) and 12(1)]cite:wipo96_wppt
  and [Article 4]cite:eurlex01_harmonisation,

- Exclusive right of communication to the public of a performance [section
  9(e)]cite:rsa78_copyrightact, [section
  106(6)]cite:usa76_title17_us_copyright_act, [Article
  11(1)(i)-(ii)]cite:wipo86_berne, [Article 8]cite:wipo96_copyright_treaty,
  [Article 13-15]cite:wipo96_wppt and [Article 3]cite:eurlex01_harmonisation,
  and

- Exclusive right[fn::Sampling constitutes an adaptation.] of adaptation,
  arrangement and other alteration [section 6(f-g)]cite:rsa78_copyrightact,
  [Article 12]cite:wipo86_berne and [Article 16]cite:wipo96_wppt.

* Bibliography                                                       :ignore:
\printbibliography

#  LocalWords:  patentable ccTLD gTLD WHOIS ICANN Sibusiso Sibusiso's
