
* LaTeX Preamble                                                     :ignore:
#+TITLE: IPSP066 - Internet Aspects of Copyright and Trade Marks
#+AUTHOR: Nyameko Lisa
#+DATE: 26 April 2018
#+SUBTITLE: Assignment 02 - 827787

#+LATEX_HEADER: \usepackage[margin=0.65in]{geometry}
#+LATEX_HEADER: \usepackage[backend=biber, style=ieee, url=false]{biblatex}
#+LATEX_HEADER: \usepackage{float}
#+LATEX_HEADER: \usepackage[super,negative]{nth}
#+LATEX_HEADER: \usepackage[capitalise]{cleveref}
#+LATEX_HEADER: \usepackage{pst-node,transparent,ragged2e}
#+LATEX_HEADER: \addbibresource{/home/nuk3/.spacemacs.d/org-files/bibliography.bib}
#+LATEX_HEADER: \DeclareFieldFormat[inproceedings]{citetitle}{\textit{#1}}
#+LATEX_HEADER: \DeclareFieldFormat[inproceedings]{title}{\textit{#1}}
#+LATEX_HEADER: \DeclareFieldFormat[misc]{citetitle}{#1}
#+LATEX_HEADER: \DeclareFieldFormat[misc]{title}{#1}
#+LATEX_HEADER: \renewcommand*{\bibpagespunct}{%
#+LATEX_HEADER:   \ifentrytype{inproceedings}
#+LATEX_HEADER:     {\addspace}
#+LATEX_HEADER:     {\addcomma\space}}
#+LATEX_HEADER: \AtEveryCitekey{\ifuseauthor{}{\clearname{author}}}
#+LATEX_HEADER: \AtEveryBibitem{\ifuseauthor{}{\clearname{author}}}

#+OPTIONS: toc:nil
#+LATEX_HEADER: \SpecialCoor

# Institution
#+BEGIN_EXPORT latex
\addvspace{110pt}
\centering{
\pnode(0.5\textwidth,-0.5\textheight){thisCenter}
\rput(thisCenter){%\transparent{0.25}
\includegraphics[width=2.7in]{/home/nuk3/course/llb/wipo-unisa/UNISACoatofArms.eps}}}
#+END_EXPORT

#+LaTeX: \justifying
#+LaTeX: \addvspace{110pt}
* Declaration
  :PROPERTIES:
   :UNNUMBERED: t
  :END:
  I know that plagiarism is to use someone else’s work and pass it off as my own.\\
  I know that plagiarism is wrong.\\
  I confirm that this assignment is my own work.\\
  I have acknowledged in the bibliography accompanying the assignment all the sources that I have used.\\
  I have not directly copied without acknowledgement anything from the Internet or from any other source.\\
  I have indicated every quotation and citation in a footnote or bracket linked to that quotation.\\
  I have not allowed anyone else to copy my work and to pass it off as their own work.\\
  I understand that if any unacknowledged copying whatsoever appears in my assignment I will receive zero per cent for the assignment.\\
  I am aware of the UNISA policy on plagiarism and understand that disciplinary proceedings can be instituted against me by UNISA if I contravene this policy.\\
  I indicate my understanding and acceptance of this declaration by
  entering my name here under:
    - Name: *Nyameko Lisa* (Student Number: *7874-909-3*)

** NOTE
Please note that footnotes will be denoted as [fn::This is a footnote.] and will
appear at the bottom of the page.\\
References will be denoted by cite:rsa93_tm_act and will appear at the end of the document.
\newpage

* Will Sibusiso be liable if consent from the rights holders has not been obtain? TO whom will he be liable?

* Where will an infringement action against him be instituted?

* What law will apply?

* Sibusiso wants to register the domain name `united'.

As per the definitions of [section 2(1)]cite:rsa93_tm_act and given that the
Republic is a Paris Convention Member State, [article 15(1)]cite:wto17_trips,
[article 1(2)]cite:wipo83_paris_conve_protect_ip, it follows that
/`UNITED.gTLD'/ and /`UNITED.ccTLD/ will be understood to be *marks*, in that
they are names or signs capable of being represented graphically. Moreover
/`UNITED.COM'/ constitutes a *well-known registered service* or *trade mark* in
the United States of America in relation to distinguishing their trade or use
from other goods or services connected in the course of trade regarding
/`airline and courier services.'/.

** Can he register such a domain name?

In order to reserve such a domain name in a general Top-Level Domain or *gTLD*,
the *registrant* Sibusiso must register it with an ICANN-accredited
registrar[fn::Or alternatively through a registrar's resellers.]
cite:icann13_rules. The registrar will then check if the UNITED.gTLD domain name
is available, and then either create or lookup a WHOIS (domain name registration
record) with the registrant's information cite:icann99_policy. The registrant would be advised
against the pursuit of gTLD of the `united' domain name, as he is not likely to
be successful. In particular, while the `united' trade mark may be territorial by
its very nature, the specific `united.com' domain name cannot be owned by
multiple companies, irrespective of the uniqueness of their products and / or
markets.\\

Alternatively, the registrant would be strongly advised to instead pursue
registration of the country code Top-Level Domain or *ccTLD* domain
`united.co.za', through one of the ccTLD operators
[section 59]cite:rsa02_elect_comm_trans_act, particularly if the students he intends to sell
sound recordings to are based within the Republic. This will be assigned on a
first-come first-serve basis.

** Could he be liable for trade mark infringement?
Yes indeed, as per the provisions of [sections 10(6) and 35]cite:rsa93_tm_act
/(for litigation within the Republic)/, [Article 16 subsections (1), (2) and
(3)]cite:wto17_trips, [Article
@@latex:6\textsuperscript{\textit{bis}}@@(1)]cite:wipo83_paris_conve_protect_ip,
[Article 16]cite:wipo70_tlt and [subsection 1125(c)]cite:usa46_title15_ch22
/(for actions within the United States of America)/, the proprietors of the
second level domain `united', as is the case with the airline company, may argue
that it is indeed a *well-known* mark and that registration of Sibusiso's domain
name in either a gTLD or ccTLD, constitutes trade mark infringement, through the
*dilution* of a well-known mark.\\

Dilution protection is not subject to the same limitations of `traditional'
trade mark infringement,[fn:1] in that it extends to use of the offending mark to
/any/ goods and services. The proprietors of the UNITED.com Airlines trade
mark and domain name, need demonstrate that:
- Their mark is well known within the Republic, i.e. it would be sufficient for
  them to show that their trade mark has acquired a reputation amongst a
  substantial number of members of the public,
  citetitle:corbett97_mcd_v_joburgers cite:corbett97_mcd_v_joburgers,
- Sibusiso has used the mark in the course of trade, where the courts of
  the Republic view this in the `traditional' trade mark infringement[fn:1]
  sense, citetitle:harms01_cowbell_v_ics cite:harms01_cowbell_v_ics, lastly
- Use of the infringing mark is likely to take unfair advantage of, or be
  detrimental to the distinctive character of the UNITED Airlines trade mark,
  amounting to unfair competition [articles 2(1) and 3(2)(a)(i)]cite:wipo96_model_provi_unfair_comp.

** Is there any other procedure that could be instituted to resolve the dispute?

ICANN provides a Uniform Domain Name Dispute Resolution Policy which outlines
provisions [section 4(a)(i)]cite:icann99_policy, within which mandatory
administrative proceedings may be instituted, on the basis that as a *third
party complainant* UNITED Airlines asserts that Sibusiso's domain is identical
or confusingly similar to their trade or service mark over which they have
rights to.

* Sibusiso wants to place samples from the sound recordings for sale on his web site.
As a Convention Member the provisions of [Article 9(1)]cite:wto17_trips,
[section 5]cite:rsa78_copyrightact, [Article 1(2)]cite:eurlex00_elec_commerce,
[Article 5(2)]cite:wipo86_berne and [Article 1(4)]cite:wipo96_copyright_treaty
which dictate that the statues of the Republic shall govern international
copyright protection as it pertains to the Internet. Furthermore as per the
provisions of [sections 1 and 2(1)(b,e)]cite:rsa78_copyrightact and [Article
2(1)]cite:wipo86_berne the sound recordings shall be considered as *protected
artistic works* or *sound recordings*.

** Which holders of intellectual property rights may be affected by this?

As per the provisions of [Article 14]cite:wto17_trips, [sections 1, 3,
4(1)(a)]cite:rsa78_copyrightact, [Articles 2 and 3]cite:wipo96_wppt, [Article 3
and 9(1)]cite:wipo86_berne, the *authors*, and they are understood to be the
performers, producers, licensees and broadcasting organisations of the sound
recordings.

** Which of their rights may be affected?
- Exclusive right of reproduction [section 9(a)]cite:rsa78_copyrightact,
  [Article 9(1) and (2)]cite:wipo86_berne, [Article 7 and 11]cite:wipo96_wppt
  and [Article 2(a-e)]cite:eurlex01_harmonisation,

- Exclusive right of offering by way of trade, directly or indirectly, a
  reproduction of the sound recording [section 9(b)]cite:rsa78_copyrightact,

- Exclusive right of publication, distribution or broadcast to the public, or
  causing the sound recording to be transmitted in a diffusion service [section
  9(c-d)]cite:rsa78_copyrightact, [Article
  11@@latex:\textsuperscript{bis}@@(1)(i)-(ii)]cite:wipo86_berne, [Article
  6(1)]cite:wipo96_copyright_treaty, [Article 8(1) and 12(1)]cite:wipo96_wppt
  and [Article 4]cite:eurlex01_harmonisation,

- Exclusive right of communication to the public of a performance [section
  9(e)]cite:rsa78_copyrightact, [Article 11(1)(i)-(ii)]cite:wipo86_berne,
  [Article 8]cite:wipo96_copyright_treaty, [Article 13-15]cite:wipo96_wppt and
  [Article 3]cite:eurlex01_harmonisation, and

- Exclusive right[fn::Sampling constitutes an adaptation.] of adaptation,
  arrangement and other alteration [section 6(f-g)]cite:rsa78_copyrightact,
  [Article 12]cite:wipo86_berne and [Article 16]cite:wipo96_wppt.

** Does he need their permission to do so? What form will such permission take?

Yes indeed, by way of a license, [section 22]cite:rsa78_copyrightact and
[Article 13(1)]cite:wipo86_berne.

** If he does not obtain their permission, will HostNet also be legally liable?

With respect to Sibusiso's intellectual property rights infringement, the
intermediary service provider HostNet shall _*not*_ be legally liable, for
activities conducted during the course of its trade:
- Information transmission or acting as a *`mere conduit'* [Article 12]cite:eurlex00_elec_commerce,
- Temporary information storage *`caching'* [Article 13]cite:eurlex00_elec_commerce, and
- Hosting [Article 14]cite:eurlex00_elec_commerce.

Moreover there exist provisions against statutory requirements obliging HostNet
to monitor Sibusiso's activities on their respective servers [Article 15]cite:eurlex00_elec_commerce.

* Bibliography                                                       :ignore:
\printbibliography

#  LocalWords:  patentable ccTLD gTLD WHOIS ICANN Sibusiso Sibusiso's

* Footnotes

[fn:1] Restricted to goods and services which are the same or similar to those for which the mark is registered.
